# .github/workflows/update-readme-cli.yml
name: Update README CLI Usage

on:
  push:
    paths:
      - "scripts/qmoi-unified-push.py"
      - "scripts/update_readme_cli.py"
      - "README.md"
  pull_request:
    paths:
      - "scripts/qmoi-unified-push.py"
      - "scripts/update_readme_cli.py"
      - "README.md"

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Run CLI updater
        run: |
          python scripts/update_readme_cli.py

      - name: Check for changes
        run: |
          git diff --quiet README.md || echo "README_UPDATED=true" >> $GITHUB_ENV

      - name: Commit and push changes
        if: env.README_UPDATED == 'true'
        run: |
          git config user.name "qmoibot"
          git config user.email "qmoibot@users.noreply.github.com"
          git add README.md
          git commit -m "docs: auto-update CLI usage in README [skip ci]"
          git push
