directories:
  output: Qmoi_apps/windows
  buildResources: build
appId: com.qmoi.ai
productName: QMOI AI
files:
  - filter:
      - main.js
      - public/**/*
      - package.json
      - icon.ico
win:
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
  icon: icon.ico
linux:
  target:
    - AppImage
    - deb
  icon: icon.png
mac:
  target:
    - dmg
    - zip
  icon: icon.icns
nsis:
  oneClick: false
  perMachine: true
  allowElevation: true
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: QMOI AI
  include: installer/installer.nsh
  license: installer/LICENSE.txt
  installerHeaderIcon: public/favicon.ico
  installerSidebar: installer/sidebar.bmp
publish:
  provider: github
  owner: thealphakenya
  repo: Alpha-Q-ai
electronVersion: 37.2.3
