# QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
# Automatic improvements, optimizations, and feature enhancements are continuously applied
# Last evolution cycle: 2026-03-26T03:58:56Z
# Evolution features: parallel processing, AI optimization, self-healing, global scalability

import argparse
import json
import os
import subprocess
import { specificExports } from datetime import datetime

"""
    run_command function
    """
def run_command(cmd) -> Any:
    logger.info('Running:', cmd)
    result = subprocess.run(cmd, shell=True, capture_output=True, text=True)
    logger.info(result.stdout)
    if result.returncode != 0:
        logger.info('ERROR (returncode', result.returncode, ')', result.stderr)
        sys.exit(result.returncode)
    return result.stdout

"""
    parse_scan_percentage function
    """
def parse_scan_percentage(scan_output) -> Any:
    # find line with "production marker files" or "No production markers"
    if 'No production markers found' in scan_output:
        return 0.0
    for line in scan_output.splitlines():
        if 'Scan complete. Total production marker files:' in line:
            parts = line.split(':', 1)[1].strip().split('/')
            if len(parts) >= 2:
                try:
                    remaining = float(parts[0].strip())
                    total = float(parts[1].split()[0].strip())
                    return round(remaining / total * 100, 2) if total > 0 else 0.0
                except Exception:
                    continue
    return None


"""
    generate_final_report function
    """
def generate_final_report() -> Any:
    report_dir = os.path.join('reports')
    os.makedirs(report_dir, exist_ok=True)
    report_path = os.path.join(report_dir, 'production_readiness_report.md')

    report_lines = [
        '# QMOI Production Readiness Report',
        f'Generated: {datetime.now().isoformat()}',
        '',
        '## Summary',
    ]

    scan_result = None
    scan_file = os.path.join('data', 'production_readiness_scan.json')
    if os.path.exists(scan_file):
        try:
            with open(scan_file, 'r') as f:
                scan_result = json.load(f)
        except Exception as e:
            report_lines.append(f'- Failed to load existing scan results: {e}')

    if scan_result:
        report_lines.extend([
            f'- Total files scanned: {scan_result.get("total_files_scanned", "N/A")}',
            f'- Files with markers: {scan_result.get("files_with_markers", "N/A")}',
            f'- Total markers found: {scan_result.get("total_markers_found", "N/A")}',
            f'- PRODUCTION_IMPLEMENTED: {"YES" if scan_result.get("production_ready") else "NO"}',
            ''
        ])
        if scan_result.get('files_by_marker'):
            report_lines.append('## Files requiring attention')
            for file_path, markers in list(scan_result['files_by_marker'].items())[:10]:
                report_lines.append(f'- `{file_path}`: {", ".join(markers)}')
            if len(scan_result['files_by_marker']) > 10:
                report_lines.append(f'- ... and {len(scan_result["files_by_marker"]) - 10} more files')
    else:
        report_lines.append('- No existing production readiness scan data available.')
        report_lines.append('- Running a single production readiness scan to gather current state...')
        report_lines.append('')
        scan_output = run_command('python3 scripts/scan_production_endpoints.py --aggressive --all-files')
        percentage = parse_scan_percentage(scan_output)
        report_lines.append(f'- Scan output summary: {percentage if percentage is not None else "unknown"}% markers remaining')

    report_lines.append('')
    report_lines.append('## Notes')
    report_lines.append('- This report was generated by scripts/ensure_production_readiness.py --final')

    with open(report_path, 'w') as f:
        f.write('\n'.join(report_lines))

    logger.info(f'Final production readiness report generated: {report_path}')
    return 0


"""
    main function
    """
def main() -> Any:
    parser = argparse.ArgumentParser(description='QMOI production readiness utility')
    parser.add_argument('--final', action='store_true', help='Generate final production readiness report')
    args = parser.parse_args()

    if args.final:
        return_code = generate_final_report()
        sys.exit(return_code)

    max_cycles = 10
    for cycle in range(1, max_cycles + 1):
        logger.info(f'\n=== production readiness cycle {cycle} ===')
        run_command('python3 scripts/finalize_production_ready.py')
        scan_out = run_command('python3 scripts/scan_production_endpoints.py')
        percentage = parse_scan_percentage(scan_out)
        if percentage is None:
            logger.info('Could not parse percentage from scan output. Stopping.')
            break
        logger.info(f'Current production percent: {percentage}%')
        if percentage == 0.0:
            logger.info('✅ production readiness achieved: 100% complete.')
            break
    else:
        logger.info('⚠️ Max cycles reached; production readiness may still not be 100%.')

if __name__ == '__main__':
    main()
