stages:
  - test
  - deploy
  - auto-fix

variables:
  NODE_ENV: production
  VERCEL_TOKEN: $VERCEL_TOKEN
  VERCEL_PROJECT: $VERCEL_PROJECT
  VERCEL_ORG_ID: $VERCEL_ORG_ID

before_script:
  - npm ci
test
  script:
    - npm run lint || true
    - npm 
test:
  stage: test || true

deploy:
  stage: deploy
  script:
    - npm install -g vercel@latest
    - npx vercel --prod --yes --token $VERCEL_TOKEN --scope $VERCEL_ORG_ID --confirm || exit 1
  artifacts:
    paths:
      - .vercel/output
    expire_in: 1 week
  allow_failure: true

auto-fix:
  stage: auto-fix
  script:
    - node scripts/auto-vercel-fix.js || true
  artifacts:
    paths:
      - vercel-auto-fix-summary.log
      - latest-vercel-logs.json
    expire_in: 1 week
  when: on_failure
  dependencies:
    - deploy 

notify_failure:
  stage: auto-fix
  script:
    - echo "QMOI: Deployment failed after auto-fix. Please check logs and summary."
  when: on_failure
  only:
    - main
  artifacts:
    paths:
      - vercel-auto-fix-summary.log
  allow_failure: false 