stages:
  - prepare
  - lint
  - test
  - build

variables:
  NODE_VERSION: "22"

prepare:
  stage: prepare
  image: node:${NODE_VERSION}
  script:
    - npm ci
  tags: []

lint:
  stage: lint
  image: node:${NODE_VERSION}
  script:
    - npm run convert:require-to-import
    - npm run lint:strict
  allow_failure: false

test:
  stage: test
  image: node:${NODE_VERSION}
  script:
    - npm test
  allow_failure: false

build:
  stage: build
  image: node:${NODE_VERSION}
  script:
    - npm run build:web
  artifacts:
    paths:
      - dist
