stages:
  - setup
  - auto-fix
  - validate
  - test
  - build
  - deploy
  - notify
  - auto-evolution
  - cleanup

variables:
  NODE_ENV: production
  CI: "true"
  QMOI_AUTO_FIX: "true"
  QMOI_NOTIFICATIONS: "true"
  QMOI_ERROR_RECOVERY: "true"

setup:
  stage: setup
  script:
    - npm install
    - npm run qmoi:setup
  artifacts:
    paths:
      - node_modules/

auto-fix:
  stage: auto-fix
  script:
    - npm run qmoi:fix
    - python scripts/qmoi-error-handler.py
  allow_failure: true

validate:
  stage: validate
  script:
    - npm run lint
    - npm run type-check
    - npm run format:check

test:
  stage: test
  script:
    - npm test
    - npm run test:coverage
    - npm run test:ui
    - npm run test:e2e
  artifacts:
    paths:
      - coverage/
      - test-results/

build:
  stage: build
  script:
    - npm run build
    - npm run build:prod
  artifacts:
    paths:
      - build/
      - dist/

deploy:
  stage: deploy
  script:
    - npm run qmoi:deploy
    - npm run gitlab:deploy
  environment:
    name: production
  only:
    - main

notify:
  stage: notify
  script:
    - npm run qmoi:notify
    - python scripts/qmoi-notifications.py
  allow_failure: true

auto-evolution:
  stage: auto-evolution
  script:
    - python scripts/qmoi-auto-evolution.py
  allow_failure: true

cleanup:
  stage: cleanup
  script:
    - npm run cleanup
  when: always