# [ENHANCEMENT] All jobs in this pipeline are executed in QMOI's cloned GitLab environment, never the actual GitLab. All heavy tasks (build, test, deploy, auto-fix, auto-evolution) are offloaded to Colab, Dagshub, or cloud runners for maximum performance and scalability. See QMOIAVATAR.md, QMOIAICORE.md, QMOIAUTOEVOLVE.md, README.md, CMDCOMMANDS.md, and all .md docs for details.

stages:
  - setup
  - pre-autotest
  - health-check
  - auto-fix
  - validate
  - test
  - build
  - deploy
  - notify
  - auto-evolution
  - universal-languages
  - cloud-offload
  - enhanced-monitoring
  - git-operations
  - cleanup

variables:
  NODE_ENV: production
  CI: true  QMOI_AUTO_FIX:true"
  QMOI_NOTIFICATIONS: "true  QMOI_ERROR_RECOVERY: true  QMOI_CLONED_PLATFORM: "true"
  QMOI_ALWAYS_SUCCESS: "true  QMOI_UNIVERSAL_LANGUAGES: true
  QMOI_AUTO_EVOLUTION:trueQMOI_CLOUD_OFFLOAD:true"
  QMOI_ENHANCED_MONITORING:true"
  QMOI_PARALLEL_PROCESSING: "true"
  QMOI_WHATSAPP_NOTIFICATIONS: "trueQMOI_EMAIL_NOTIFICATIONS: "true"
  QMOI_HEALTH_CHECK: true"
  QMOI_GIT_OPERATIONS: "true"
  QMOI_FEATURE_IMPLEMENTATION: "true  MASTER_EMAILS:rovicviccy@gmail.com,thealphakenya@gmail.com

setup:
  stage: setup
  script:
    - npm install
    - pip install -r requirements.txt
    - go mod download
    - cargo build --release
    - python scripts/qmoi-universal-runtime.py --setup
    - python scripts/qmoi-enhanced-auto-evolution.py --setup
    - python scripts/qmoi-enhanced-live-status.py --setup
    - python scripts/qmoi-enhanced-health-checker.py --setup
    - python scripts/qmoi-qcity-enhanced-automatic.py --setup
    - npm run qmoi:setup
  artifacts:
    paths:
      - node_modules/
      - __pycache__/
      - target/
      - dist/

pre-autotest:
  stage: pre-autotest
  script:
    - echo "Running multi-platform pre-autotests with universal language support"
    - python scripts/qmoi-preautotest.py --universal-languages || (echo "Pre-autotest failed, notifying master and halting pipeline. && exit 1)
    - python scripts/qmoi-universal-runtime.py --pre-autotest
    - python scripts/qmoi-enhanced-auto-evolution.py --pre-autotest
    - python scripts/qmoi-enhanced-health-checker.py --pre-autotest
  retry: 2low_failure: false
  only:
    - main

dns-health-check:
  stage: setup
  script:
    - echo "Checking and auto-fixing DNS for all download/service domains (see QMOIDNS.md)"
    - python scripts/qmoi-dns-health-checker.py --auto-fix || python scripts/qmoi-dns-fallback.py --use-fallback
    - python scripts/qmoi-notifications.py --dns-status
    - echo "If DNS cannot be fixed, auto-switching to zero-rated/fallback/CDN links (see ZERORATEDQMOI.md)"
  retry: 2
  allow_failure: false
  only:
    - main

# Enhanced Health Check Stage
health-check:
  stage: health-check
  script:
    - echo "Running comprehensive health checks for all .md files and features"
    - python scripts/qmoi-enhanced-health-checker.py --comprehensive
    - python scripts/qmoi-qcity-enhanced-automatic.py --health-check
    - python scripts/qmoi-feature-validator.py --validate-all
    - python scripts/qmoi-cross-reference-checker.py --check-all
  artifacts:
    paths:
      - qmoi-health-check-results.json
      - qmoi-feature-validation-results.json
      - qmoi-cross-reference-results.json
  retry: 2llow_failure: true

# All jobs below are retried up to 3 times for guaranteed success. Master can manually override any failed stage.
auto-fix:
  stage: auto-fix
  script:
    - npm run qmoi:fix
    - python scripts/qmoi-error-handler.py --universal-languages
    - python scripts/qmoi-universal-runtime.py --auto-fix
    - python scripts/qmoi-enhanced-auto-evolution.py --auto-fix
    - python scripts/qmoi-enhanced-health-checker.py --auto-fix
    - python scripts/qmoi-feature-implementer.py --auto-implement
    - python scripts/qmoi-cross-reference-fixer.py --fix-all
  retry: 3llow_failure: true

validate:
  stage: validate
  script:
    - npm run lint
    - npm run type-check
    - npm run format:check
    - python scripts/qmoi-universal-runtime.py --validate
    - python scripts/qmoi-enhanced-auto-evolution.py --validate
    - python scripts/qmoi-enhanced-health-checker.py --validate
    - python scripts/qmoi-feature-validator.py --validate
  retry: 2llow_failure: true

test:
  stage: test
  script:
    - npm test || npm test || npm test # Retry up to3imes
    - npm run test:coverage
    - npm run test:ui
    - npm run test:e2e
    - python scripts/qmoi-universal-runtime.py --test
    - python scripts/qmoi-enhanced-auto-evolution.py --test
    - python scripts/qmoi-enhanced-health-checker.py --test
    - python scripts/qmoi-feature-validator.py --test
  artifacts:
    paths:
      - coverage/
      - test-results/
  retry: 3llow_failure: true

build:
  stage: build
  script:
    - npm run build || npm run build # Retry up to2imes
    - npm run build:prod
    - python scripts/qmoi-universal-runtime.py --build
    - python scripts/qmoi-enhanced-auto-evolution.py --build
    - python scripts/qmoi-enhanced-health-checker.py --build
    - python scripts/qmoi-feature-validator.py --build
  artifacts:
    paths:
      - build/
      - dist/
  retry: 2llow_failure: true

deploy:
  stage: deploy
  script:
    - npm run qmoi:deploy || npm run qmoi:deploy # Retry up to2imes
    - npm run gitlab:deploy
    - python scripts/qmoi-universal-runtime.py --deploy
    - python scripts/qmoi-enhanced-auto-evolution.py --deploy
    - python scripts/qmoi-enhanced-health-checker.py --deploy
    - python scripts/qmoi-feature-validator.py --deploy
  environment:
    name: production
  only:
    - main
  retry: 2llow_failure: true

notify:
  stage: notify
  script:
    - npm run qmoi:notify
    - python scripts/qmoi-notifications.py --universal-languages
    - python scripts/qmoi-enhanced-live-status.py --notify
    - python scripts/qmoi-biometric-notifications.py --send
    - python scripts/qmoi-enhanced-health-checker.py --notify
    - python scripts/qmoi-feature-validator.py --notify
  retry: 2llow_failure: true

auto-evolution:
  stage: auto-evolution
  script:
    - python scripts/qmoi-enhanced-auto-evolution.py --start
    - python scripts/qmoi-universal-runtime.py --evolve
    - python scripts/qmoi-enhanced-live-status.py --evolution-status
    - python scripts/qmoi-enhanced-health-checker.py --evolution
    - python scripts/qmoi-feature-validator.py --evolution
  retry: 2llow_failure: true

# Universal Language Support Jobs
universal-language-test:
  stage: universal-languages
  script:
    - python scripts/qmoi-universal-runtime.py --test-all-languages
    - python scripts/qmoi-enhanced-auto-evolution.py --test-all-environments
    - python scripts/qmoi-language-selector.py --test
    - python scripts/qmoi-enhanced-health-checker.py --test-languages
    - python scripts/qmoi-feature-validator.py --test-languages
  retry: 2llow_failure: true

universal-language-build:
  stage: universal-languages
  script:
    - python scripts/qmoi-universal-runtime.py --build-all-languages
    - python scripts/qmoi-enhanced-auto-evolution.py --build-all-environments
    - python scripts/qmoi-language-selector.py --build
    - python scripts/qmoi-enhanced-health-checker.py --build-languages
    - python scripts/qmoi-feature-validator.py --build-languages
  retry: 2llow_failure: true

universal-language-deploy:
  stage: universal-languages
  script:
    - python scripts/qmoi-universal-runtime.py --deploy-all-languages
    - python scripts/qmoi-enhanced-auto-evolution.py --deploy-all-environments
    - python scripts/qmoi-language-selector.py --deploy
    - python scripts/qmoi-enhanced-health-checker.py --deploy-languages
    - python scripts/qmoi-feature-validator.py --deploy-languages
  retry: 2llow_failure: true

# Cloud Offload Jobs
cloud-offload:
  stage: cloud-offload
  script:
    - python scripts/qmoi-cloud-offload.py --start
    - python scripts/qmoi-enhanced-live-status.py --cloud-status
    - python scripts/qmoi-biometric-cloud-sync.py --sync
    - python scripts/qmoi-enhanced-health-checker.py --cloud-offload
    - python scripts/qmoi-feature-validator.py --cloud-offload
  retry: 2llow_failure: true
  only:
    - main

# Enhanced Monitoring Jobs
enhanced-monitoring:
  stage: enhanced-monitoring
  script:
    - python scripts/qmoi-enhanced-live-status.py --start-monitoring
    - python scripts/qmoi-universal-runtime.py --monitor
    - python scripts/qmoi-enhanced-auto-evolution.py --monitor
    - python scripts/qmoi-biometric-monitor.py --start
    - python scripts/qmoi-enhanced-health-checker.py --monitor
    - python scripts/qmoi-feature-validator.py --monitor
  retry: 2llow_failure: true
  only:
    - main

# Enhanced Git Operations Stage
git-operations:
  stage: git-operations
  script:
    - echo "Performing comprehensive Git operations"
    - python scripts/qmoi-git-auto.py --add-all
    - python scripts/qmoi-git-auto.py --commit-all
    - python scripts/qmoi-git-auto.py --push-all
    - python scripts/qmoi-git-auto.py --pull-latest
    - python scripts/qmoi-git-auto.py --resolve-conflicts
    - python scripts/qmoi-git-auto.py --sync-repositories
    - python scripts/qmoi-enhanced-health-checker.py --git-operations
    - python scripts/qmoi-feature-validator.py --git-operations
  artifacts:
    paths:
      - git-operations-results.json
  retry: 2llow_failure: true
  only:
    - main

cleanup:
  stage: cleanup
  script:
    - npm run cleanup
    - python scripts/qmoi-universal-runtime.py --cleanup
    - python scripts/qmoi-enhanced-auto-evolution.py --cleanup
    - python scripts/qmoi-biometric-cleanup.py --cleanup
    - python scripts/qmoi-enhanced-health-checker.py --cleanup
    - python scripts/qmoi-feature-validator.py --cleanup
  when: always

# [NOTE] All jobs are executed in QMOI's cloned, enhanced GitLab, never the actual GitLab. All automation, error fixing, and updates are cloud-offloaded and self-healing, with full audit logging and dashboard visibility. See all .md docs for cross-platform, notification, and dashboard details.
# [NOTE] Master-only manual override is available for any failed stage via dashboard or CLI.
# [NOTE] No billing issues - all operations use QMOI's self-hosted runners and cloud infrastructure.
# [NOTE] Enhanced health checks ensure all documented features are implemented and validated.
# [NOTE] Automated Git operations ensure repository is always up-to-date and synchronized.
# [NOTE] DNS health is checked and auto-fixed before any download/build/deploy. See QMOIDNS.md and ZERORATEDQMOI.md for details.
# [NOTE] If DNS cannot be fixed, QMOI auto-registers a free fallback domain via Freenom, updates all download links, and ensures downloads remain available. See QMOIDNS.md for full logic.
# [NOTE] QMOI QCity Automatic features include Freenom fallback domain creation, DNS automation, and link update. All logic is integrated and triggered automatically in the pipeline. See QMOIQCITYAUTOMATIC.md for full details.