stages:
  - test

e2e_tests:
  image: cypress/browsers:node20.10.0-chrome120-ff120
  stage: test
  script:
    - npm ci
    - npm run build
    - npx cypress run
  artifacts:
    paths:
      - cypress/videos
      - cypress/screenshots
    expire_in: 1 week
  after_script:
    # Upload to Codecov (set CODECOV_TOKEN in CI/CD variables if private)
    - bash <(curl -s https://codecov.io/bash) -f coverage/lcov.info
    # Upload to Coveralls
    - npm install -g coveralls
    - cat coverage/lcov.info | coveralls 