name: Deploy to Railway

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Debug Secrets
        run: |
          if [[ -z "${{ secrets.RAILWAY_TOKEN }}" ]]; then
            echo "❌ RAILWAY_TOKEN is missing!"
            exit 1
          fi
          echo "✅ RAILWAY_TOKEN is set."

      - name: Build Docker image
        run: |
          docker --version  # Check if docker is installed
          docker build -t my-docker-image:${{ github.sha }} .
          docker images  # List images to check if the build was successful

      - name: Push Docker image to Docker Hub
        run: |
          docker --version  # Check if docker is installed
          docker push my-docker-image:${{ github.sha }}
          
      - name: Install Railway CLI
        run: |
          echo "Installing Railway CLI..."
          curl -fsSL https://railway.app/install.sh | sh
          echo "$HOME/.railway/bin" >> $GITHUB_PATH
          echo "$HOME/.railway/bin" >> $GITHUB_ENV
          railway --version  # Ensure the CLI is correctly installed

      - name: Log into Railway
        run: |
          echo "Logging into Railway..."
          railway login --token ${{ secrets.RAILWAY_TOKEN }}

      - name: Deploy to Railway using Docker Hub image
        run: |
          echo "Deploying to Railway..."
          railway init  # Ensure Railway is initialized
          railway link  # Ensure the project is linked to Railway
          railway up --image my-docker-image:${{ github.sha }}

      - name: Debug Deployment (if failed)
        if: failure()
        run: |
          echo "🚨 Deployment failed. Checking logs..."
          railway logs --tail