# ensure_build_files.py
import os

# Required files with minimal content
def ensure_file(path, content=""):
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(content)
            print(f"✅ Created missing file: {path}")

# Public icon fallback
ensure_file("public/favicon.ico", "")

# Minimal NSIS installer script
ensure_file("installer/installer.nsh", "!include \"MUI2.nsh\"\nName \"QMOI App\"\nOutFile \"QMOIAppSetup.exe\"\nInstallDir $PROGRAMFILES\\QMOIApp\nSection \"Install\"\n  SetOutPath $INSTDIR\n  File \"..\\build\\QMOIApp.exe\"\nSectionEnd\n")

# License
ensure_file("installer/LICENSE.txt", "MIT License\n\nGenerated by QMOI AI")

# Icon fallback
if not os.path.exists("icon.ico"):
    os.system("python generate_icon.py")
