import js from "@eslint/js";
import typescript from "@typescript-eslint/eslint-plugin";
import typescriptParser from "@typescript-eslint/parser";

export default [
  js.configs.recommended,
  {
    files: [
      "**/*.ts",
      "**/*.tsx",
      "src/**/*.ts",
      "src/**/*.tsx",
      "components/**/*.tsx",
    ],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        window: "readonly",
        document: "readonly",
        localStorage: "readonly",
        navigator: "readonly",
        fetch: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        CustomEvent: "readonly",
        SpeechSynthesisUtterance: "readonly",
        HTMLVideoElement: "readonly",
        HTMLCanvasElement: "readonly",
        CanvasRenderingContext2D: "readonly",
        URL: "readonly",
        File: "readonly",
        console: "readonly",
        exports: "readonly",
        global: "readonly",
        Blob: "readonly",
        Notification: "readonly",
        Audio: "readonly",
        alert: "readonly",
        confirm: "readonly",
        prompt: "readonly",
        btoa: "readonly",
        atob: "readonly",
        HTMLElement: "readonly",
        HTMLDivElement: "readonly",
        HTMLParagraphElement: "readonly",
        HTMLHeadingElement: "readonly",
        HTMLButtonElement: "readonly",
        HTMLInputElement: "readonly",
        HTMLTextAreaElement: "readonly",
        HTMLSelectElement: "readonly",
        HTMLUListElement: "readonly",
        HTMLOListElement: "readonly",
        HTMLLIElement: "readonly",
        HTMLAnchorElement: "readonly",
        HTMLSpanElement: "readonly",
        HTMLTableElement: "readonly",
        HTMLTableSectionElement: "readonly",
        HTMLTableRowElement: "readonly",
        HTMLTableCellElement: "readonly",
        HTMLTableCaptionElement: "readonly",
        EventTarget: "readonly",
        Window: "readonly",
        SpeechSynthesisVoice: "readonly",
        process: "readonly",
        Storage: "readonly",
        Console: "readonly",
        Response: "readonly",
        SpeechSynthesisErrorEvent: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": typescript,
    },
    rules: {
      ...typescript.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: [
      "scripts/**/*.js",
      "scripts/**/*.ts",
      "backend/**/*.ts",
      "lib/**/*.ts",
      "whatsapp-qmoi-bot/**/*.js",
      "ssh-backend/**/*.js",
    ],
    languageOptions: {
      parser: typescriptParser,
      parserOptions: {
        ecmaVersion: "latest",
        sourceType: "module",
      },
      globals: {
        require: "readonly",
        module: "writable",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        setInterval: "readonly",
        clearInterval: "readonly",
        setTimeout: "readonly",
        clearTimeout: "readonly",
        console: "readonly",
        exports: "readonly",
        global: "readonly",
        btoa: "readonly",
        atob: "readonly",
        EventTarget: "readonly",
      },
    },
    plugins: {
      "@typescript-eslint": typescript,
    },
    rules: {
      ...typescript.configs.recommended.rules,
      "@typescript-eslint/no-explicit-any": "warn",
      "@typescript-eslint/no-require-imports": "off",
      "@typescript-eslint/explicit-function-return-type": "off",
      "@typescript-eslint/explicit-module-boundary-types": "off",
      "@typescript-eslint/no-unused-vars": [
        "warn",
        { argsIgnorePattern: "^_" },
      ],
    },
  },
  {
    files: [
      "**/__tests__/**/*.{js,ts,tsx}",
      "**/tests/**/*.{js,ts}",
      "**/*.spec.{js,ts}",
      "**/*.test.{js,ts,tsx}",
      "tests/**/*.js",
      "tests/**/*.ts",
      "cypress/**/*.js",
    ],

    languageOptions: {
      globals: {
        describe: "readonly",
        it: "readonly",
        test: "readonly",
        expect: "readonly",
        beforeAll: "readonly",
        afterAll: "readonly",
        cy: "readonly",
        require: "readonly",
        Buffer: "readonly",
        console: "readonly",
        process: "readonly",
      },
    },
  },
  {
    files: [
      "start-watchdebug.js",
      "watchdebug.js",
      "mp-inspect.js",
      "test-getHandlers.js",
      "test-msw.js",
      "test-msw-node.js",
      "tools/**/*.js",
    ],
    languageOptions: {
      globals: {
        require: "readonly",
        module: "writable",
        process: "readonly",
        __dirname: "readonly",
        __filename: "readonly",
        Buffer: "readonly",
        console: "readonly",
      },
    },
  }
];
