#!/usr/bin/env python3
"""
Regenerate `ALLMDFILESREFS.md` by scanning the repository for `.md` files.

This is safer than hand-editing the big index and ensures newly created markdown files
are listed there.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'ALLMDFILESREFS.md'

def scan_md():
    md_files = []
    for root, dirs, files in os.walk(ROOT):
        # skip typical vendor/cache dirs
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__', '.venv', 'venv')]
        for f in files:
            if f.lower().endswith('.md'):
                p = Path(root) / f
                rel = p.relative_to(ROOT).as_posix()
                md_files.append(rel)
    return sorted(md_files)

def write_index(md_files):
    header = ['# All Markdown Files References', '', 'Generated by tools/update_all_md_refs.py', '']
    lines = header + [f'- {p}' for p in md_files]
    OUT.write_text('\n'.join(lines), encoding='utf-8')

def main():
    md_files = scan_md()
    write_index(md_files)
    print(f'Wrote {OUT} with {len(md_files)} .md files')

if __name__ == '__main__':
    main()
#!/usr/bin/env python3
"""
Regenerate `ALLMDFILESREFS.md` by scanning the repository for `.md` files.

This is safer than hand-editing the big index and ensures newly created markdown files
are listed there.
"""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'ALLMDFILESREFS.md'

def scan_md():
    md_files = []
    for root, dirs, files in os.walk(ROOT):
        # skip typical vendor/cache dirs
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__', '.venv', 'venv')]
        for f in files:
            if f.lower().endswith('.md'):
                p = Path(root) / f
                rel = p.relative_to(ROOT).as_posix()
                md_files.append(rel)
    return sorted(md_files)

def write_index(md_files):
    header = ['# All Markdown Files References', '', 'Generated by tools/update_all_md_refs.py', '']
    lines = header + [f'- {p}' for p in md_files]
    OUT.write_text('\n'.join(lines), encoding='utf-8')

def main():
    md_files = scan_md()
    write_index(md_files)
    print(f'Wrote {OUT} with {len(md_files)} .md files')

if __name__ == '__main__':
    main()
