<!-- AUTODEV Enhanced: 2026-04-20T09:07:31.607478 -->
<!-- AUTODEV Enhanced: 2026-04-20T09:01:09.648201 -->
<!-- AUTODEV Enhanced: 2026-04-20T08:55:05.319812 -->
.nh
.TH "GH-REPO-LICENSE-LIST" "1" "Mar 2026" "GitHub CLI 2.89.0" "GitHub CLI manual"

.SH NAME
gh-repo-license-list - List common repository licenses


.SH SYNOPSIS
\fBgh repo license list [flags]\fR


.SH DESCRIPTION
List common repository licenses.

.PP
For even more licenses, visit 
\[la]https://choosealicense.com/appendix\[ra]


.SH ALIASES
gh repo license ls


.SH EXIT CODES
0: Successful execution

.PP
1: Error

.PP
2: Command canceled

.PP
4: Authentication required

.PP
NOTE: Specific commands may have additional exit codes. Refer to the command's help for more information.


.SH SEE ALSO
\fBgh-repo-license(1)\fR
