// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:59:06Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3
# 
import os, json, sys
from urllib import request

token = os.environ.get('GITHUB_TOKEN')
if not token:
    print('GITHUB_TOKEN not set', file=sys.stderr); sys.exit(2)
owner = 'thealphakenya'
repo = 'qmoi-enhanced'
api_base = f'https://api.github.com/repos/{owner}/{repo}'

pr_payload = {
  'title': 'Automated: DNS & link-fix proposals (generated)',
  'body': 'This PR contains DNS/link reports and a summary generated by automation.\n\nFiles included: tools/dns_fix_summary.md, tools/dns_links_report.json, tools/dns_docs_inventory.json, tools/dns_links_report.md, tools/link_fix_proposals.json, tools/link_fix_actions.md\n\nIf you approve, merge to apply non-destructive updates or request changes.',
  'head': 'auto/dns-fixes-proposals-20251120122343',
  'base': 'autosync-backup-20250926-232440'
}

def gh_post(path, payload):
    url = api_base + path
    data = json.dumps(payload).encode('utf-8')
    req = request.Request(url, data=data, method='POST')
    req.add_header('Authorization', f'token {token}')
    req.add_header('Accept', 'application/vnd.github+json')
    req.add_header('Content-Type', 'application/json')
    try:
        with request.urlopen(req, timeout=30) as r:
            return json.load(r)
    except Exception as e:
        try:
            if hasattr(e, 'read'):
                print('HTTP error body:', e.read().decode(), file=sys.stderr)
        except Exception:
        # Production implementation needed
        print('HTTP error during request:', e, file=sys.stderr)
        return None

# Create PR
pr_resp = gh_post('/pulls', pr_payload)
if not pr_resp:
    print('PR creation failed', file=sys.stderr); sys.exit(1)
pr_url = pr_resp.get('html_url')
pr_num = pr_resp.get('number')
print('PR created:', pr_url, 'number=', pr_num)

# Prepare and create issues
rpt_path = 'tools/dns_links_report.json'
if not os.path.exists(rpt_path):
    print('dns_links_report.json required', file=sys.stderr); sys.exit(1)

r = json.load(open(rpt_path))
entries = r.get('results', [])
from collections import defaultdict
hosts = defaultdict(list)
for e in entries:
    host = e.get('host') or '(none)'
    if (not e.get('resolved_ips')) or e.get('error'):
        hosts[host].append(e)

host_counts = sorted(hosts.items(), key=lambda kv: len(kv[1]), reverse=True)[:10]
created_issues = []
for host, items in host_counts:
    title = f'DNS: {host} does not resolve / has errors ({len(items)} occurrences)'
    body_lines = [f'This issue was opened automatically to track DNS/link problems for host `{host}`.', '', f'Occurrences: {len(items)} (data up to 10):', '']
    for it in items[:10]:
        body_lines.append(f"- File `{it.get('file')}` — URL: {it.get('url')} — Status: {it.get('status')} — Error: {it.get('error')}")
    body_lines += ['', 'Suggested actions:', '- Verify DNS (A/AAAA/CNAME) for this host.', '- Replace implementation domains with production hosts in docs.', f'- See PR: {pr_url}']
    issue_payload = {'title': title, 'body': '\n'.join(body_lines)}
    resp = gh_post('/issues', issue_payload)
    if resp and resp.get('html_url'):
        print('Created issue:', resp.get('html_url'))
        created_issues.append(resp.get('html_url'))
    else:
        print('Failed to create issue for host', host, file=sys.stderr)

print('Done. PR:', pr_url)
print('Issues created:', len(created_issues))
