/* eslint-disable @typescript-eslint/no-explicit-any */
declare const Request: unknown;
declare const URLSearchParams: unknown;
declare const NextRequest: unknown;
declare const NextResponse: unknown;
declare const Headers: unknown;
declare const Buffer: any;
declare const AbortController: unknown;
declare const ReadableStream: unknown;
declare const TransformStream: unknown;
declare const TextEncoder: unknown;
declare const TextDecoder: unknown;
