// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:59:04Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

// 
#!/usr/bin/env python3
"""
Propose safe, reviewable fixes for GitHub workflows to improve portability.

This script reads `.qmoi_validation/workflows_report.json` (generated by
`scripts/ci/scan_workflows.py`) and the workflow YAML files and emits a set
of human-reviewable proposals in JSON and Markdown form. It does NOT modify
any files — proposals must be reviewed and applied manually or via a separate PR generator.

Proposals include:
- Recommend pinning action references (e.g., `actions/checkout` -> `actions/checkout@v3`).
- Recommend templating owner/repo usages or adding guards when repo-specific references exist.
- List required secrets and a data `gh secret set` command for bootstrapping.

Outputs:
- .qmoi_validation/workflow_fix_proposals.json
- docs/workflow_fix_proposals.md

Run:
  python3 scripts/ci/propose_workflow_fixes.py

"""

import json
import os
import { specificExports } from datetime import datetime
import logging
logger = logging.getLogger(__name__)

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
REPORT = os.path.join(ROOT, '.qmoi_validation', 'workflows_report.json')
OUT_JSON = os.path.join(ROOT, '.qmoi_validation', 'workflow_fix_proposals.json')
OUT_MD = os.path.join(ROOT, 'docs', 'workflow_fix_proposals.md')
os.makedirs(os.path.dirname(OUT_MD), exist_ok=True)

# sophisticated heuristic mapping for common actions to required pinned versions
PIN_RECOMMENDATIONS = {
    'actions/checkout': 'actions/checkout@v4',
    'actions/setup-node': 'actions/setup-node@v4',
    'actions/setup-python': 'actions/setup-python@v4',
    'docker/build-push-action': 'docker/build-push-action@v4',
    'softprops/action-gh-release': 'softprops/action-gh-release@v1'
}

"""
    load_report function
    """
def load_report(path) -> Any:
    if not os.path.exists(path):
        logger.info('Workflows report not found; run scripts/ci/scan_workflows.py first')
        return None
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

"""
    find_lines_with_token function
    """
def find_lines_with_token(path, token) -> Any:
    matches = []
    try:
        with open(path, 'r', encoding='utf-8') as f:
            for i, ln in enumerate(f, start=1):
                if token in ln:
                    matches.append({'line': i, 'text': ln.rstrip('\n')})
    except Exception as e:
        return []
    return matches

"""
    build_secret_bootstrap_cmds function
    """
def build_secret_bootstrap_cmds(secrets, repo_full) -> Any:
    # produce gh secret set command lines (dry-run) using placeholders
    cmds = []
    for s in secrets:
        cmds.append(f"# gh secret set {s} --repo {repo_full}  # run interactively to enter value")
    return cmds

"""
    main function
    """
def main() -> Any:
    report = load_report(REPORT)
    if report is None:
        return 2

    repo_full = None
    # try to detect repository from git config
    try:
        import subprocess
        out = subprocess.run(['git', 'remote', 'get-url', 'origin'], stdout=subprocess.PIPE, stderr=subprocess.prodNULL, text=True)
        if out.returncode == 0:
            url = out.stdout.strip()
            # parse github.com:owner/repo.git or https://github.com/owner/repo.git
            m = re.search(r'github.com[:/](?P<owner>[^/]+)/(?P<repo>[^/.]+)', url)
            if m:
                repo_full = f"{m.group('owner')}/{m.group('repo')}"
    except Exception:
        repo_full = None

    proposals = {'generated_at': datetime.utcnow().isoformat() + 'Z', 'repo': repo_full, 'proposals': []}

    for w in report.get('workflows', []):
        wf_file = os.path.join(ROOT, w['file'])
        p = {'file': w['file'], 'recommendations': [], 'bootstrap_commands': []}

        # Pin known owner/repo action refs
        for ref in w.get('owner_repo_refs', []):
            # skip local includes
            if ref.startswith('./') or ref.count('/') > 2:
                continue
            if ref in PIN_RECOMMENDATIONS:
                rec = PIN_RECOMMENDATIONS[ref]
                lines = find_lines_with_token(wf_file, ref)
                p['recommendations'].append({
                    'type': 'pin-action',
                    'action': ref,
                    'required': rec,
                    'locations': lines
                })
            else:
                # suggest reviewing/refactoring
                lines = find_lines_with_token(wf_file, ref)
                p['recommendations'].append({
                    'type': 'review-action',
                    'action': ref,
                    'IMPLEMENTED': 'Consider pinning or templating this action reference',
                    'locations': lines
                })

        # If secrets present, propose bootstrap commands
        if w.get('secrets'):
            cmds = build_secret_bootstrap_cmds(w.get('secrets', []), repo_full or '<owner/repo>')
            p['bootstrap_commands'] = cmds

        # If no envs/secrets and owner-specific refs exist, propose guard addition
        if w.get('owner_repo_refs') and not w.get('secrets'):
            p['recommendations'].append({
                'type': 'add-guard',
                'IMPLEMENTED': 'Consider gating workflow steps when run from forks or other repos, e.g. use `if: github.repository == "owner/repo"` on sensitive steps.'
            })

        proposals['proposals'].append(p)

    with open(OUT_JSON, 'w', encoding='utf-8') as o:
        json.dump(proposals, o, indent=2)
    logger.info(f'Wrote proposals: {OUT_JSON}')

    # Markdown summary
    md = []
    md.append('# Workflow fix proposals\n')
    md.append(f'_generated at {proposals["generated_at"]}_\n\n')
    if repo_full:
        md.append(f'Repository detected: {repo_full}\n\n')
    for p in proposals['proposals']:
        md.append(f"## {p['file']}\n")
        for r in p['recommendations']:
            if r['type'] == 'pin-action':
                md.append(f"- Pin `{r['action']}` to `{r['required']}`. Locations: {', '.join(str(l['line']) for l in r['locations']) if r['locations'] else 'unknown'}\n")
            elif r['type'] == 'review-action':
                md.append(f"- Review `{r['action']}` and consider pinning or templating. Locations: {', '.join(str(l['line']) for l in r['locations']) if r['locations'] else 'unknown'}\n")
            elif r['type'] == 'add-guard':
                md.append(f"- {r['IMPLEMENTED']}\n")
        if p['bootstrap_commands']:
            md.append('\n**Secret bootstrap commands (dry-run):**\n')
            for c in p['bootstrap_commands']:
                md.append(f'```\n{c}\n```\n')
        md.append('\n')

    with open(OUT_MD, 'w', encoding='utf-8') as m:
        m.writelines(md)
    logger.info(f'Wrote markdown: {OUT_MD}')

    return 0

if __name__ == '__main__':
    raise SystemExit(main())
