#!/usr/bin/env python3
"""
Settle discovered wallet balances into the canonical Cashon ledger.

Safe-by-default: dry-run and mock. To enable real transfers you must set
PRODUCTION_CONFIRMED=true in the environment and pass --real on the CLI.

This script reads `.qmoi_validation/all_wallets_qvs.json` (a list of wallet
reports produced by `scripts/wallets/check_wallets.py`) and writes a
settlement/ledger entry to `.qmoi_validation/cashon_ledger.json` (appends).

No real network calls are made unless --real + PRODUCTION_CONFIRMED=true.
If you enable real mode you must edit the CASHON_API_URL and provide credentials
via environment variables and follow the production runbook.
"""

import argparse
import json
import os
import re
from datetime import datetime

BASE_DIR = os.path.abspath(os.path.join(os.path.dirname(__file__), '..', '..'))
VALIDATION_DIR = os.path.join(BASE_DIR, '.qmoi_validation')
WALLETS_REPORT = os.path.join(VALIDATION_DIR, 'all_wallets_qvs.json')
LEDGER_FILE = os.path.join(VALIDATION_DIR, 'cashon_ledger.json')

AMOUNT_RE = re.compile(r"[-+]?[0-9]+(?:\.[0-9]+)?")

def parse_amount(s):
    if s is None:
        return 0.0
    m = AMOUNT_RE.search(str(s))
    if not m:
        return 0.0
    try:
        return float(m.group(0))
    except Exception:
        return 0.0

def load_wallets(path):
    if not os.path.exists(path):
        print(f"Wallets report not found: {path} — creating empty list")
        return []
    with open(path, 'r', encoding='utf-8') as f:
        return json.load(f)

def append_ledger(entry, path):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    ledger = []
    if os.path.exists(path):
        try:
            with open(path, 'r', encoding='utf-8') as f:
                ledger = json.load(f)
        except Exception:
            ledger = []
    ledger.append(entry)
    with open(path, 'w', encoding='utf-8') as f:
        json.dump(ledger, f, indent=2, ensure_ascii=False)
    print(f"Wrote ledger with {len(ledger)} entries to {path}")

def main():
    p = argparse.ArgumentParser()
    p.add_argument('--report', default=LEDGER_FILE, help='Path to write the cashon ledger JSON')
    p.add_argument('--wallets', default=WALLETS_REPORT, help='Wallets report to read')
    p.add_argument('--real', action='store_true', help='Execute real transfers (requires PRODUCTION_CONFIRMED=true)')
    args = p.parse_args()

    wallets = load_wallets(args.wallets)
    items = []
    total = 0.0
    for w in wallets:
        # Accept either dict-shaped wallet reports or simple strings (file paths)
        if isinstance(w, dict):
            wdict = w
        else:
            wdict = {'source_file': str(w), 'balance': None}

        # Each wallet report may store `balance` or `meta.balance` or `result` etc.
        bal = None
        for key in ('balance', 'available', 'result', 'amount'):
            if key in wdict:
                bal = wdict.get(key)
                break
        if bal is None:
            # try known shapes
            if 'meta' in wdict and isinstance(wdict['meta'], dict) and 'balance' in wdict['meta']:
                bal = wdict['meta']['balance']

        amt = parse_amount(bal)
        total += amt
        items.append({
            'wallet_id': wdict.get('id') or wdict.get('name') or wdict.get('source_file') or 'unknown',
            'currency': wdict.get('currency', 'UNK'),
            'balance_raw': bal,
            'amount': amt,
            'status': wdict.get('status', 'unknown')
        })

    timestamp = datetime.utcnow().isoformat() + 'Z'
    ledger_entry = {
        'timestamp': timestamp,
        'items': items,
        'total_amount': total,
        'settled_to': 'CASHON (dry-run)' if not args.real else 'CASHON (real)',
        'note': 'Auto-generated by scripts/finance/settle_to_cashon.py'
    }

    # Real transfer gating
    if args.real:
        if os.environ.get('PRODUCTION_CONFIRMED', '').lower() != 'true':
            print('Refusing to perform real transfers: PRODUCTION_CONFIRMED!=true')
            return 2
        # Placeholder: here we would call the Cashon API to transfer funds or record receipts.
        # Example (NOT IMPLEMENTED):
        # cashon_url = os.environ.get('CASHON_API_URL')
        # cashon_key = os.environ.get('CASHON_API_KEY')
        # call cashon API to credit total into the Cashon wallet and record transaction id.
        # For safety this repo intentionally requires manual implementation of the real API steps.
        ledger_entry['note'] += ' (requested real transfer; no live API implemented in repo)'
        ledger_entry['real_transfer_executed'] = False
    else:
        ledger_entry['note'] += ' (dry-run; no transfer executed)'

    append_ledger(ledger_entry, args.report)
    print(f"Total amount aggregated: {total}")
    return 0

if __name__ == '__main__':
    raise SystemExit(main())
