export interface AvatarConfig {
  id: string;
  name: string;
  type:
    | "human"
    | "animal"
    | "robot"
    | "fantasy"
    | "bird"
    | "sea-creature"
    | "mythical";
  category: string;
  description: string;
  features: string[];
  animationEngine:
    | "framer-motion"
    | "three-js"
    | "eva3d-sadtalker"
    | "nerf-face"
    | "gaussian-splatting"
    | "luma-ai"
    | "pika-labs";
  qualityLevel: "standard" | "enhanced" | "ultra" | "ai-enhanced";
  voiceProfile?: string;
  assetPath: string;
  thumbnailPath: string;
  environment?: string;
  props?: string[];
  gestures?: string[];
  expressions?: string[];
  isActive: boolean;
  isPremium?: boolean;
  autoUpgrade?: boolean;
}

export const avatarsConfig: AvatarConfig[] = [
  // Original Avatars (Enhanced)
  {
    id: "default",
    name: "Default QMOI",
    type: "human",
    category: "Professional",
    description:
      "The classic QMOI avatar with professional appearance and gestures.",
    features: ["wave", "smile", "presentation", "business attire"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "ai-enhanced",
    voiceProfile: "professional-male",
    assetPath: "/avatars/default/",
    thumbnailPath: "/avatars/default/thumbnail.png",
    environment: "office",
    props: ["chair", "desk"],
    gestures: ["wave", "point", "present", "think"],
    expressions: ["smile", "focused", "confident", "curious"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "lion",
    name: "Lion Aviator",
    type: "animal",
    category: "Wild",
    description: "Majestic lion avatar representing strength and leadership.",
    features: ["roar", "mane", "proud stance", "savanna background"],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "lion-roar",
    assetPath: "/avatars/lion/",
    thumbnailPath: "/avatars/lion/thumbnail.png",
    environment: "savanna",
    props: ["throne", "crown"],
    gestures: ["roar", "pounce", "survey", "command"],
    expressions: ["majestic", "fierce", "wise", "protective"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "young-boy",
    name: "Young Boy Aviator",
    type: "human",
    category: "Youth",
    description: "Energetic young boy avatar with playful and curious nature.",
    features: ["wave", "smile", "playful", "casual attire"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "young-male",
    assetPath: "/avatars/young-boy/",
    thumbnailPath: "/avatars/young-boy/thumbnail.png",
    environment: "playground",
    props: ["toy", "ball"],
    gestures: ["wave", "jump", "play", "explore"],
    expressions: ["excited", "curious", "happy", "surprised"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "young-girl",
    name: "Young Girl Aviator",
    type: "human",
    category: "Youth",
    description: "Bright young girl avatar with intelligence and creativity.",
    features: ["wave", "smile", "creative", "colorful attire"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "young-female",
    assetPath: "/avatars/young-girl/",
    thumbnailPath: "/avatars/young-girl/thumbnail.png",
    environment: "art-studio",
    props: ["paintbrush", "canvas"],
    gestures: ["wave", "paint", "dance", "create"],
    expressions: ["creative", "bright", "focused", "joyful"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "robot",
    name: "Robot Aviator",
    type: "robot",
    category: "Technology",
    description:
      "Advanced AI robot avatar with futuristic design and capabilities.",
    features: [
      "mechanical movements",
      "holographic displays",
      "cyberpunk style",
    ],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "robotic-ai",
    assetPath: "/avatars/robot/",
    thumbnailPath: "/avatars/robot/thumbnail.png",
    environment: "cyberpunk-city",
    props: ["hologram", "energy-core"],
    gestures: ["mechanical-wave", "hologram-project", "scan", "transform"],
    expressions: ["digital", "analytical", "futuristic", "efficient"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "elder",
    name: "Elder Aviator",
    type: "human",
    category: "Wisdom",
    description: "Wise elder avatar representing knowledge and experience.",
    features: ["wise gestures", "calm demeanor", "traditional attire"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "elder-male",
    assetPath: "/avatars/elder/",
    thumbnailPath: "/avatars/elder/thumbnail.png",
    environment: "library",
    props: ["book", "staff"],
    gestures: ["bless", "teach", "contemplate", "guide"],
    expressions: ["wise", "calm", "knowing", "gentle"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "cat",
    name: "Cat Aviator",
    type: "animal",
    category: "Domestic",
    description: "Playful and curious cat avatar with feline grace.",
    features: ["purr", "stretch", "playful", "elegant movements"],
    animationEngine: "three-js",
    qualityLevel: "enhanced",
    voiceProfile: "cat-purr",
    assetPath: "/avatars/cat/",
    thumbnailPath: "/avatars/cat/thumbnail.png",
    environment: "garden",
    props: ["yarn", "cushion"],
    gestures: ["stretch", "purr", "pounce", "groom"],
    expressions: ["curious", "content", "playful", "elegant"],
    isActive: true,
    autoUpgrade: true,
  },

  // New Man Aviator
  {
    id: "man",
    name: "Man Aviator",
    type: "human",
    category: "Professional",
    description: "Confident, animated man avatar with professional gestures.",
    features: ["wave", "smile", "presentation", "business attire"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "ai-enhanced",
    voiceProfile: "confident-male",
    assetPath: "/avatars/man/",
    thumbnailPath: "/avatars/man/thumbnail.png",
    environment: "boardroom",
    props: ["briefcase", "presentation"],
    gestures: ["wave", "present", "handshake", "direct"],
    expressions: ["confident", "professional", "focused", "friendly"],
    isActive: true,
    autoUpgrade: true,
  },

  // Sea Creatures
  {
    id: "dolphin",
    name: "Dolphin Aviator",
    type: "sea-creature",
    category: "Ocean",
    description: "Playful dolphin avatar, representing water/sea creatures.",
    features: ["jump", "splash", "whistle", "sea background"],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "dolphin-whistle",
    assetPath: "/avatars/dolphin/",
    thumbnailPath: "/avatars/dolphin/thumbnail.png",
    environment: "ocean",
    props: ["wave", "coral"],
    gestures: ["jump", "splash", "whistle", "swim"],
    expressions: ["playful", "intelligent", "friendly", "free"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "octopus",
    name: "Octopus Aviator",
    type: "sea-creature",
    category: "Ocean",
    description: "Intelligent octopus avatar with animated tentacles.",
    features: ["tentacle wave", "ink splash", "underwater", "multi-tasking"],
    animationEngine: "gaussian-splatting",
    qualityLevel: "ai-enhanced",
    voiceProfile: "octopus-bubble",
    assetPath: "/avatars/octopus/",
    thumbnailPath: "/avatars/octopus/thumbnail.png",
    environment: "deep-sea",
    props: ["treasure", "coral"],
    gestures: ["tentacle-wave", "ink-splash", "multi-task", "explore"],
    expressions: ["intelligent", "curious", "mysterious", "playful"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "whale",
    name: "Whale Aviator",
    type: "sea-creature",
    category: "Ocean",
    description: "Gentle whale avatar, representing sea creatures.",
    features: ["spout", "deep dive", "ocean background", "sing"],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "whale-song",
    assetPath: "/avatars/whale/",
    thumbnailPath: "/avatars/whale/thumbnail.png",
    environment: "deep-ocean",
    props: ["bubble", "plankton"],
    gestures: ["spout", "dive", "sing", "swim"],
    expressions: ["gentle", "wise", "peaceful", "majestic"],
    isActive: true,
    autoUpgrade: true,
  },

  // Birds (New Category)
  {
    id: "eagle",
    name: "Eagle Aviator",
    type: "bird",
    category: "Birds of Prey",
    description: "Majestic eagle avatar with soaring and keen vision.",
    features: ["soar", "screech", "mountain background", "sharp vision"],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "eagle-screech",
    assetPath: "/avatars/eagle/",
    thumbnailPath: "/avatars/eagle/thumbnail.png",
    environment: "mountain-peak",
    props: ["nest", "prey"],
    gestures: ["soar", "screech", "survey", "dive"],
    expressions: ["majestic", "focused", "powerful", "keen"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "parrot",
    name: "Parrot Aviator",
    type: "bird",
    category: "Tropical Birds",
    description:
      "Colorful and intelligent parrot avatar with mimicry abilities.",
    features: ["mimic", "colorful feathers", "tropical background", "playful"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "parrot-mimic",
    assetPath: "/avatars/parrot/",
    thumbnailPath: "/avatars/parrot/thumbnail.png",
    environment: "rainforest",
    props: ["perch", "fruit"],
    gestures: ["mimic", "dance", "preen", "play"],
    expressions: ["intelligent", "playful", "colorful", "social"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "owl",
    name: "Owl Aviator",
    type: "bird",
    category: "Nocturnal Birds",
    description: "Wise owl avatar with nocturnal wisdom and silent flight.",
    features: ["hoot", "night vision", "forest background", "wisdom"],
    animationEngine: "three-js",
    qualityLevel: "enhanced",
    voiceProfile: "owl-hoot",
    assetPath: "/avatars/owl/",
    thumbnailPath: "/avatars/owl/thumbnail.png",
    environment: "moonlit-forest",
    props: ["tree-branch", "book"],
    gestures: ["hoot", "turn-head", "fly-silent", "observe"],
    expressions: ["wise", "observant", "calm", "knowledgeable"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "falcon",
    name: "Falcon Aviator",
    type: "bird",
    category: "Birds of Prey",
    description: "Swift falcon avatar with incredible speed and precision.",
    features: ["dive", "speed", "desert background", "precision"],
    animationEngine: "three-js",
    qualityLevel: "ultra",
    voiceProfile: "falcon-cry",
    assetPath: "/avatars/falcon/",
    thumbnailPath: "/avatars/falcon/thumbnail.png",
    environment: "desert-sky",
    props: ["prey", "wind"],
    gestures: ["dive", "soar-fast", "strike", "glide"],
    expressions: ["focused", "swift", "precise", "powerful"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "swan",
    name: "Swan Aviator",
    type: "bird",
    category: "Water Birds",
    description: "Elegant swan avatar with graceful movements and beauty.",
    features: ["glide", "elegant", "lake background", "graceful"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "swan-song",
    assetPath: "/avatars/swan/",
    thumbnailPath: "/avatars/swan/thumbnail.png",
    environment: "serene-lake",
    props: ["water-lily", "reflection"],
    gestures: ["glide", "preen", "dance", "swim"],
    expressions: ["elegant", "graceful", "beautiful", "serene"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "peacock",
    name: "Peacock Aviator",
    type: "bird",
    category: "Exotic Birds",
    description: "Colorful peacock avatar with magnificent tail display.",
    features: ["display", "colorful", "garden background", "majestic"],
    animationEngine: "gaussian-splatting",
    qualityLevel: "ai-enhanced",
    voiceProfile: "peacock-call",
    assetPath: "/avatars/peacock/",
    thumbnailPath: "/avatars/peacock/thumbnail.png",
    environment: "royal-garden",
    props: ["feathers", "fountain"],
    gestures: ["display-tail", "strut", "dance", "show"],
    expressions: ["proud", "colorful", "majestic", "confident"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "hummingbird",
    name: "Hummingbird Aviator",
    type: "bird",
    category: "Small Birds",
    description: "Tiny hummingbird avatar with incredible speed and agility.",
    features: ["hover", "fast-wing", "flower background", "agile"],
    animationEngine: "three-js",
    qualityLevel: "enhanced",
    voiceProfile: "hummingbird-buzz",
    assetPath: "/avatars/hummingbird/",
    thumbnailPath: "/avatars/hummingbird/thumbnail.png",
    environment: "flower-garden",
    props: ["flower", "nectar"],
    gestures: ["hover", "dart", "feed", "dance"],
    expressions: ["quick", "energetic", "precise", "delicate"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "penguin",
    name: "Penguin Aviator",
    type: "bird",
    category: "Flightless Birds",
    description:
      "Adorable penguin avatar with waddling charm and cold weather adaptation.",
    features: ["waddle", "slide", "antarctic background", "charming"],
    animationEngine: "eva3d-sadtalker",
    qualityLevel: "enhanced",
    voiceProfile: "penguin-chirp",
    assetPath: "/avatars/penguin/",
    thumbnailPath: "/avatars/penguin/thumbnail.png",
    environment: "antarctic",
    props: ["ice", "fish"],
    gestures: ["waddle", "slide", "dive", "huddle"],
    expressions: ["adorable", "friendly", "determined", "social"],
    isActive: true,
    autoUpgrade: true,
  },

  // Mythical Creatures
  {
    id: "dragon",
    name: "Dragon Aviator",
    type: "mythical",
    category: "Fantasy",
    description: "Mythical dragon avatar with fire and flight animations.",
    features: ["fire breath", "fly", "roar", "fantasy background"],
    animationEngine: "gaussian-splatting",
    qualityLevel: "ai-enhanced",
    voiceProfile: "dragon-roar",
    assetPath: "/avatars/dragon/",
    thumbnailPath: "/avatars/dragon/thumbnail.png",
    environment: "fantasy-realm",
    props: ["treasure", "fire"],
    gestures: ["breathe-fire", "fly", "roar", "guard"],
    expressions: ["majestic", "powerful", "wise", "protective"],
    isActive: true,
    autoUpgrade: true,
  },
  {
    id: "phoenix",
    name: "Phoenix Aviator",
    type: "mythical",
    category: "Fantasy",
    description: "Immortal phoenix avatar with rebirth and fire abilities.",
    features: ["rebirth", "fire-wings", "eternal", "majestic"],
    animationEngine: "luma-ai",
    qualityLevel: "ai-enhanced",
    voiceProfile: "phoenix-song",
    assetPath: "/avatars/phoenix/",
    thumbnailPath: "/avatars/phoenix/thumbnail.png",
    environment: "eternal-flame",
    props: ["fire", "ash"],
    gestures: ["rise-from-ash", "spread-wings", "soar", "heal"],
    expressions: ["eternal", "majestic", "renewing", "powerful"],
    isActive: true,
    autoUpgrade: true,
  },
];

export const voiceProfiles = [
  {
    id: "professional-male",
    name: "Professional Male",
    type: "human",
    quality: "ai-enhanced",
  },
  {
    id: "confident-male",
    name: "Confident Male",
    type: "human",
    quality: "ai-enhanced",
  },
  { id: "young-male", name: "Young Male", type: "human", quality: "enhanced" },
  {
    id: "young-female",
    name: "Young Female",
    type: "human",
    quality: "enhanced",
  },
  { id: "elder-male", name: "Elder Male", type: "human", quality: "enhanced" },
  { id: "robotic-ai", name: "Robotic AI", type: "robot", quality: "ultra" },
  { id: "lion-roar", name: "Lion Roar", type: "animal", quality: "ultra" },
  { id: "cat-purr", name: "Cat Purr", type: "animal", quality: "enhanced" },
  {
    id: "dolphin-whistle",
    name: "Dolphin Whistle",
    type: "sea-creature",
    quality: "ultra",
  },
  {
    id: "octopus-bubble",
    name: "Octopus Bubble",
    type: "sea-creature",
    quality: "ai-enhanced",
  },
  {
    id: "whale-song",
    name: "Whale Song",
    type: "sea-creature",
    quality: "ultra",
  },
  {
    id: "eagle-screech",
    name: "Eagle Screech",
    type: "bird",
    quality: "ultra",
  },
  {
    id: "parrot-mimic",
    name: "Parrot Mimic",
    type: "bird",
    quality: "enhanced",
  },
  { id: "owl-hoot", name: "Owl Hoot", type: "bird", quality: "enhanced" },
  { id: "falcon-cry", name: "Falcon Cry", type: "bird", quality: "ultra" },
  { id: "swan-song", name: "Swan Song", type: "bird", quality: "enhanced" },
  {
    id: "peacock-call",
    name: "Peacock Call",
    type: "bird",
    quality: "ai-enhanced",
  },
  {
    id: "hummingbird-buzz",
    name: "Hummingbird Buzz",
    type: "bird",
    quality: "enhanced",
  },
  {
    id: "penguin-chirp",
    name: "Penguin Chirp",
    type: "bird",
    quality: "enhanced",
  },
  {
    id: "dragon-roar",
    name: "Dragon Roar",
    type: "mythical",
    quality: "ai-enhanced",
  },
  {
    id: "phoenix-song",
    name: "Phoenix Song",
    type: "mythical",
    quality: "ai-enhanced",
  },
];

export const animationEngines = {
  "framer-motion": {
    name: "Framer Motion",
    description: "2D animations with smooth transitions and gestures",
    quality: "standard",
    resourceUsage: "low",
    bestFor: ["simple avatars", "low-resource devices", "quick prototypes"],
  },
  "three-js": {
    name: "Three.js 3D",
    description: "3D animations with realistic lighting and physics",
    quality: "enhanced",
    resourceUsage: "medium",
    bestFor: ["3D avatars", "complex animations", "immersive experiences"],
  },
  "eva3d-sadtalker": {
    name: "EVA3D + SadTalker",
    description: "Advanced 3D talking head with realistic lip sync",
    quality: "ultra",
    resourceUsage: "high",
    bestFor: ["human avatars", "speech synthesis", "realistic expressions"],
  },
  "nerf-face": {
    name: "NeRF + Face Model",
    description: "Neural radiance fields for photorealistic faces",
    quality: "ai-enhanced",
    resourceUsage: "very-high",
    bestFor: ["photorealistic avatars", "high-end devices", "research"],
  },
  "gaussian-splatting": {
    name: "Gaussian Splatting",
    description: "Real-time 3D rendering with neural graphics",
    quality: "ai-enhanced",
    resourceUsage: "high",
    bestFor: ["complex 3D scenes", "real-time rendering", "advanced graphics"],
  },
  "luma-ai": {
    name: "Luma AI",
    description: "AI-powered 3D generation and animation",
    quality: "ai-enhanced",
    resourceUsage: "very-high",
    bestFor: [
      "AI-generated content",
      "creative projects",
      "futuristic avatars",
    ],
  },
  "pika-labs": {
    name: "Pika Labs",
    description: "AI video generation and animation",
    quality: "ai-enhanced",
    resourceUsage: "high",
    bestFor: ["video content", "dynamic scenes", "creative storytelling"],
  },
};

export const qualityLevels = {
  standard: {
    name: "Standard",
    description: "Basic quality suitable for all devices",
    features: ["basic animations", "standard voice", "simple effects"],
  },
  enhanced: {
    name: "Enhanced",
    description: "Improved quality with better animations and voice",
    features: ["smooth animations", "enhanced voice", "basic effects"],
  },
  ultra: {
    name: "Ultra",
    description: "High quality with advanced features",
    features: ["3D animations", "ultra voice", "advanced effects"],
  },
  "ai-enhanced": {
    name: "AI Enhanced",
    description: "Top-tier quality with AI-powered features",
    features: ["AI animations", "realistic voice", "premium effects"],
  },
};
