apiVersion: v1
kind: Service
metadata:
  name: qmoi-metrics
  labels:
    app: qmoi
spec:
  selector:
    app: qmoi
  ports:
    - name: metrics
      port: 9187
      targetPort: 9187
  type: ClusterIP
