// QMOI EVOLUTION ENHANCED: Global News & Intelligence Notification System
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-04-07T00:00:00Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

import React, { useState, useEffect, createContext, useContext } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { Badge } from '@/components/ui/badge';
import { useToast } from '@/hooks/use-toast';
import {
  Bell, DollarSign, TrendingUp, AlertTriangle, CheckCircle, XCircle,
  Clock, Globe, Newspaper, Radio, MapPin, Users, BarChart3,
  Mail, MessageSquare, Phone, Smartphone, Monitor, Volume2
} from 'lucide-react';

interface GlobalNewsItem {
  id: string;
  title: string;
  content: string;
  source: string;
  category: 'politics' | 'economy' | 'technology' | 'health' | 'environment' | 'sports' | 'entertainment' | 'breaking';
  importance: 'low' | 'medium' | 'high' | 'critical';
  location: {
    country: string;
    region: string;
    continent: string;
  };
  timestamp: string;
  tags: string[];
  aiAnalysis: {
    sentiment: 'positive' | 'negative' | 'neutral';
    impact: number; // 0-100
    relevance: number; // 0-100
    summary: string;
  };
}

interface DailyReport {
  id: string;
  type: 'country' | 'continent' | 'global';
  target: string; // Country name, continent name, or "Global"
  date: string;
  frequency: 'morning' | 'midday' | 'evening' | 'critical';
  sections: {
    news: GlobalNewsItem[];
    economic: any[];
    security: any[];
    weather: any[];
    aiInsights: string[];
  };
  summary: string;
  generatedAt: string;
}

interface EnhancedNotification extends FinancialNotification {
  newsItems?: GlobalNewsItem[];
  dailyReports?: DailyReport[];
  userType: 'master' | 'premium' | 'standard' | 'basic';
  deliveryChannels: ('email' | 'sms' | 'push' | 'inapp' | 'voice')[];
  autoGenerated: boolean;
  qmoiInitiated: boolean;
}

interface GlobalNotificationContextValue {
  notifications: EnhancedNotification[];
  unreadCount: number;
  isLoading: boolean;
  globalNews: GlobalNewsItem[];
  dailyReports: DailyReport[];
  markAsRead: (id: string) => void;
  markAllAsRead: () => void;
  deleteNotification: (id: string) => void;
  sendNotification: (notification: Omit<EnhancedNotification, 'id' | 'timestamp'>) => void;
  getNotificationsByType: (type: EnhancedNotification['type']) => EnhancedNotification[];
  getCriticalNotifications: () => EnhancedNotification[];
  getGlobalNews: (filters?: { category?: string; importance?: string; country?: string }) => GlobalNewsItem[];
  getDailyReports: (type?: 'country' | 'continent' | 'global', target?: string) => DailyReport[];
  subscribeToUpdates: (callback: (notification: EnhancedNotification) => void) => () => void;
  sendGlobalNewsAlert: (newsItem: GlobalNewsItem, masterId: string) => void;
  generateDailyReport: (type: 'country' | 'continent' | 'global', target: string, frequency: DailyReport['frequency']) => Promise<DailyReport>;
}

const GlobalNotificationContext = createContext<GlobalNotificationContextValue | null>(null);

export const useGlobalNotifications = () => {
  const ctx = useContext(GlobalNotificationContext);
  if (!ctx) throw new Error('useGlobalNotifications must be used within GlobalNotificationProvider');
  return ctx;
};

interface GlobalNotificationProviderProps {
  children: React.ReactNode;
  masterId: string;
}

export const GlobalNotificationProvider: React.FC<GlobalNotificationProviderProps> = ({
  children,
  masterId
}) => {
  const [notifications, setNotifications] = useState<EnhancedNotification[]>([]);
  const [globalNews, setGlobalNews] = useState<GlobalNewsItem[]>([]);
  const [dailyReports, setDailyReports] = useState<DailyReport[]>([]);
  const [isLoading, setIsLoading] = useState(false);
  const { toast } = useToast();

  useEffect(() => {
    loadNotifications();
    loadGlobalNews();
    loadDailyReports();
    // Set up real-time subscription
    const unsubscribe = subscribeToRealTimeUpdates();
    // Set up daily report generation
    setupDailyReportSchedule();
    return unsubscribe;
  }, [masterId]);

  const loadNotifications = async () => {
    try {
      setIsLoading(true);
      const response = await fetch(`/api/notifications/enhanced/${masterId}`);
      if (response.ok) {
        const data = await response.json();
        setNotifications(data);
      }
    } catch (error) {
      console.error('Failed to load notifications:', error);
    } finally {
      setIsLoading(false);
    }
  };

  const loadGlobalNews = async () => {
    try {
      const response = await fetch('/api/global-news');
      if (response.ok) {
        const data = await response.json();
        setGlobalNews(data);
      }
    } catch (error) {
      console.error('Failed to load global news:', error);
    }
  };

  const loadDailyReports = async () => {
    try {
      const response = await fetch('/api/daily-reports');
      if (response.ok) {
        const data = await response.json();
        setDailyReports(data);
      }
    } catch (error) {
      console.error('Failed to load daily reports:', error);
    }
  };

  const subscribeToRealTimeUpdates = () => {
    const eventSource = new EventSource(`/api/notifications/stream/enhanced/${masterId}`);

    eventSource.onmessage = (event) => {
      const data = JSON.parse(event.data);

      if (data.type === 'notification') {
        const notification: EnhancedNotification = data.data;
        setNotifications(prev => [notification, ...prev]);

        // Show toast for high-priority notifications
        if (notification.priority === 'high' || notification.priority === 'critical') {
          toast({
            title: notification.title,
            description: notification.message,
            variant: notification.status === 'failed' ? 'destructive' : 'default'
          });
        }
      } else if (data.type === 'global_news') {
        const newsItem: GlobalNewsItem = data.data;
        setGlobalNews(prev => [newsItem, ...prev]);

        // Auto-send critical news to master
        if (newsItem.importance === 'critical') {
          sendGlobalNewsAlert(newsItem, masterId);
        }
      } else if (data.type === 'daily_report') {
        const report: DailyReport = data.data;
        setDailyReports(prev => [report, ...prev]);
      }
    };

    eventSource.onerror = (error) => {
      console.error('Notification stream error:', error);
    };

    return () => eventSource.close();
  };

  const setupDailyReportSchedule = () => {
    // Generate reports at scheduled times
    const generateScheduledReports = async () => {
      const now = new Date();
      const hour = now.getHours();

      // Morning reports (6 AM)
      if (hour === 6) {
        await generateGlobalReport('morning');
      }
      // Midday reports (12 PM)
      else if (hour === 12) {
        await generateGlobalReport('midday');
      }
      // Evening reports (6 PM)
      else if (hour === 18) {
        await generateGlobalReport('evening');
      }
    };

    // Check every hour
    const interval = setInterval(generateScheduledReports, 60 * 60 * 1000);
    return () => clearInterval(interval);
  };

  const generateGlobalReport = async (frequency: DailyReport['frequency']) => {
    try {
      // Generate global report
      const globalReport = await generateDailyReport('global', 'Global', frequency);

      // Generate continent reports
      const continents = ['Africa', 'Asia', 'Europe', 'North America', 'South America', 'Australia', 'Antarctica'];
      for (const continent of continents) {
        await generateDailyReport('continent', continent, frequency);
      }

      // Generate country reports (sample of major countries)
      const majorCountries = ['United States', 'China', 'India', 'Brazil', 'Russia', 'Japan', 'Germany', 'United Kingdom', 'France', 'Italy'];
      for (const country of majorCountries) {
        await generateDailyReport('country', country, frequency);
      }

      toast({
        title: 'Daily Reports Generated',
        description: `Generated ${1 + continents.length + majorCountries.length} reports for ${frequency}`
      });
    } catch (error) {
      console.error('Failed to generate global reports:', error);
    }
  };

  const markAsRead = async (id: string) => {
    try {
      await fetch(`/api/notifications/${id}/read`, { method: 'PUT' });
      setNotifications(prev =>
        prev.map(n => n.id === id ? { ...n, read: true } : n)
      );
    } catch (error) {
      console.error('Failed to mark notification as read:', error);
    }
  };

  const markAllAsRead = async () => {
    try {
      await fetch(`/api/notifications/mark-all-read/${masterId}`, { method: 'PUT' });
      setNotifications(prev => prev.map(n => ({ ...n, read: true })));
    } catch (error) {
      console.error('Failed to mark all notifications as read:', error);
    }
  };

  const deleteNotification = async (id: string) => {
    try {
      await fetch(`/api/notifications/${id}`, { method: 'DELETE' });
      setNotifications(prev => prev.filter(n => n.id !== id));
    } catch (error) {
      console.error('Failed to delete notification:', error);
    }
  };

  const sendNotification = async (notification: Omit<EnhancedNotification, 'id' | 'timestamp'>) => {
    try {
      const response = await fetch('/api/notifications/enhanced', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ ...notification, masterId })
      });

      if (response.ok) {
        const newNotification = await response.json();
        setNotifications(prev => [newNotification, ...prev]);
      }
    } catch (error) {
      console.error('Failed to send notification:', error);
    }
  };

  const sendGlobalNewsAlert = async (newsItem: GlobalNewsItem, masterId: string) => {
    const notification: Omit<EnhancedNotification, 'id' | 'timestamp'> = {
      type: 'alert',
      title: `🚨 CRITICAL: ${newsItem.title}`,
      message: newsItem.aiAnalysis.summary,
      status: 'completed',
      priority: 'critical',
      location: newsItem.location,
      metadata: {
        newsId: newsItem.id,
        category: newsItem.category,
        importance: newsItem.importance
      },
      userType: 'master',
      deliveryChannels: ['email', 'sms', 'push', 'inapp', 'voice'],
      autoGenerated: true,
      qmoiInitiated: true,
      newsItems: [newsItem]
    };

    await sendNotification(notification);
  };

  const generateDailyReport = async (
    type: 'country' | 'continent' | 'global',
    target: string,
    frequency: DailyReport['frequency']
  ): Promise<DailyReport> => {
    const response = await fetch('/api/daily-reports/generate', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ type, target, frequency })
    });

    if (!response.ok) {
      throw new Error('Failed to generate daily report');
    }

    const report = await response.json();
    setDailyReports(prev => [report, ...prev]);
    return report;
  };

  const getNotificationsByType = (type: EnhancedNotification['type']) => {
    return notifications.filter(n => n.type === type);
  };

  const getCriticalNotifications = () => {
    return notifications.filter(n => n.priority === 'critical');
  };

  const getGlobalNews = (filters?: { category?: string; importance?: string; country?: string }) => {
    let filtered = globalNews;

    if (filters?.category) {
      filtered = filtered.filter(n => n.category === filters.category);
    }
    if (filters?.importance) {
      filtered = filtered.filter(n => n.importance === filters.importance);
    }
    if (filters?.country) {
      filtered = filtered.filter(n => n.location.country === filters.country);
    }

    return filtered;
  };

  const getDailyReports = (type?: 'country' | 'continent' | 'global', target?: string) => {
    let filtered = dailyReports;

    if (type) {
      filtered = filtered.filter(r => r.type === type);
    }
    if (target) {
      filtered = filtered.filter(r => r.target === target);
    }

    return filtered;
  };

  const unreadCount = notifications.filter(n => !n.read).length;

  return (
    <GlobalNotificationContext.Provider value={{
      notifications,
      unreadCount,
      isLoading,
      globalNews,
      dailyReports,
      markAsRead,
      markAllAsRead,
      deleteNotification,
      sendNotification,
      getNotificationsByType,
      getCriticalNotifications,
      getGlobalNews,
      getDailyReports,
      subscribeToUpdates: subscribeToRealTimeUpdates,
      sendGlobalNewsAlert,
      generateDailyReport
    }}>
      {children}
    </GlobalNotificationContext.Provider>
  );
};

interface GlobalNewsCardProps {
  newsItem: GlobalNewsItem;
  onViewDetails: (newsItem: GlobalNewsItem) => void;
}

export const GlobalNewsCard: React.FC<GlobalNewsCardProps> = ({ newsItem, onViewDetails }) => {
  const getImportanceColor = (importance: GlobalNewsItem['importance']) => {
    switch (importance) {
      case 'critical': return 'border-red-500 bg-red-50';
      case 'high': return 'border-orange-500 bg-orange-50';
      case 'medium': return 'border-yellow-500 bg-yellow-50';
      case 'low': return 'border-green-500 bg-green-50';
      default: return 'border-gray-500 bg-gray-50';
    }
  };

  const getCategoryIcon = (category: GlobalNewsItem['category']) => {
    switch (category) {
      case 'politics': return <Users className="w-4 h-4" />;
      case 'economy': return <TrendingUp className="w-4 h-4" />;
      case 'technology': return <Monitor className="w-4 h-4" />;
      case 'health': return <AlertTriangle className="w-4 h-4" />;
      case 'breaking': return <Radio className="w-4 h-4" />;
      default: return <Newspaper className="w-4 h-4" />;
    }
  };

  return (
    <Card className={`p-4 border-l-4 ${getImportanceColor(newsItem.importance)} cursor-pointer hover:shadow-md transition-shadow`}
          onClick={() => onViewDetails(newsItem)}>
      <div className="flex items-start justify-between mb-2">
        <div className="flex items-center space-x-2">
          {getCategoryIcon(newsItem.category)}
          <Badge variant="outline" className="text-xs">
            {newsItem.category.toUpperCase()}
          </Badge>
          <Badge className={getImportanceColor(newsItem.importance)} variant="outline">
            {newsItem.importance.toUpperCase()}
          </Badge>
        </div>
        <div className="flex items-center space-x-1 text-xs text-gray-500">
          <MapPin className="w-3 h-3" />
          <span>{newsItem.location.country}</span>
        </div>
      </div>

      <h3 className="font-semibold text-sm mb-2">{newsItem.title}</h3>
      <p className="text-xs text-gray-600 mb-2 line-clamp-2">{newsItem.content}</p>

      <div className="flex items-center justify-between text-xs text-gray-500">
        <span>{newsItem.source}</span>
        <span>{new Date(newsItem.timestamp).toLocaleString()}</span>
      </div>

      {newsItem.aiAnalysis && (
        <div className="mt-2 p-2 bg-blue-50 rounded text-xs">
          <div className="font-semibold text-blue-700">AI Analysis:</div>
          <div className="text-blue-600">{newsItem.aiAnalysis.summary}</div>
          <div className="flex items-center space-x-2 mt-1">
            <span>Impact: {newsItem.aiAnalysis.impact}/100</span>
            <span>Relevance: {newsItem.aiAnalysis.relevance}/100</span>
          </div>
        </div>
      )}
    </Card>
  );
};

interface DailyReportCardProps {
  report: DailyReport;
  onViewReport: (report: DailyReport) => void;
}

export const DailyReportCard: React.FC<DailyReportCardProps> = ({ report, onViewReport }) => {
  const getTypeIcon = (type: DailyReport['type']) => {
    switch (type) {
      case 'global': return <Globe className="w-5 h-5 text-blue-500" />;
      case 'continent': return <MapPin className="w-5 h-5 text-green-500" />;
      case 'country': return <BarChart3 className="w-5 h-5 text-purple-500" />;
      default: return <Newspaper className="w-5 h-5 text-gray-500" />;
    }
  };

  const getFrequencyColor = (frequency: DailyReport['frequency']) => {
    switch (frequency) {
      case 'critical': return 'bg-red-100 text-red-800';
      case 'morning': return 'bg-orange-100 text-orange-800';
      case 'midday': return 'bg-yellow-100 text-yellow-800';
      case 'evening': return 'bg-blue-100 text-blue-800';
      default: return 'bg-gray-100 text-gray-800';
    }
  };

  return (
    <Card className="p-4 cursor-pointer hover:shadow-md transition-shadow"
          onClick={() => onViewReport(report)}>
      <div className="flex items-center justify-between mb-3">
        <div className="flex items-center space-x-2">
          {getTypeIcon(report.type)}
          <h3 className="font-semibold">{report.target}</h3>
        </div>
        <Badge className={getFrequencyColor(report.frequency)} variant="outline">
          {report.frequency.toUpperCase()}
        </Badge>
      </div>

      <p className="text-sm text-gray-600 mb-3 line-clamp-3">{report.summary}</p>

      <div className="flex items-center justify-between text-xs text-gray-500">
        <div className="flex space-x-4">
          <span>News: {report.sections.news.length}</span>
          <span>AI Insights: {report.sections.aiInsights.length}</span>
        </div>
        <span>{new Date(report.generatedAt).toLocaleString()}</span>
      </div>
    </Card>
  );
};

interface GlobalNotificationCenterProps {
  masterId: string;
}

export const GlobalNotificationCenter: React.FC<GlobalNotificationCenterProps> = ({ masterId }) => {
  const {
    notifications,
    unreadCount,
    isLoading,
    globalNews,
    dailyReports,
    markAsRead,
    markAllAsRead,
    deleteNotification,
    getGlobalNews,
    getDailyReports,
    generateDailyReport
  } = useGlobalNotifications();

  const [activeTab, setActiveTab] = useState<'notifications' | 'news' | 'reports'>('notifications');
  const [newsFilters, setNewsFilters] = useState({
    category: '',
    importance: '',
    country: ''
  });
  const [selectedNewsItem, setSelectedNewsItem] = useState<GlobalNewsItem | null>(null);
  const [selectedReport, setSelectedReport] = useState<DailyReport | null>(null);

  const filteredNews = getGlobalNews(newsFilters);
  const recentReports = getDailyReports().slice(0, 10);

  const handleGenerateReport = async (type: 'country' | 'continent' | 'global', target: string) => {
    try {
      await generateDailyReport(type, target, 'critical');
    } catch (error) {
      console.error('Failed to generate report:', error);
    }
  };

  if (isLoading) {
    return <div className="flex justify-center items-center h-64">Loading global notifications...</div>;
  }

  return (
    <div className="max-w-7xl mx-auto p-6">
      <div className="mb-6">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h1 className="text-3xl font-bold mb-2">Global Intelligence Center</h1>
            <p className="text-gray-600">Real-time global news, notifications, and daily reports</p>
          </div>
          <div className="flex items-center space-x-4">
            {unreadCount > 0 && (
              <Badge variant="destructive" className="px-3 py-1">
                {unreadCount} unread notifications
              </Badge>
            )}
            <Badge variant="outline" className="px-3 py-1">
              {globalNews.length} news items
            </Badge>
            <Badge variant="outline" className="px-3 py-1">
              {dailyReports.length} reports
            </Badge>
          </div>
        </div>

        <div className="flex space-x-1 mb-4">
          <Button
            variant={activeTab === 'notifications' ? 'default' : 'outline'}
            onClick={() => setActiveTab('notifications')}
          >
            <Bell className="w-4 h-4 mr-2" />
            Notifications ({notifications.length})
          </Button>
          <Button
            variant={activeTab === 'news' ? 'default' : 'outline'}
            onClick={() => setActiveTab('news')}
          >
            <Newspaper className="w-4 h-4 mr-2" />
            Global News ({globalNews.length})
          </Button>
          <Button
            variant={activeTab === 'reports' ? 'default' : 'outline'}
            onClick={() => setActiveTab('reports')}
          >
            <BarChart3 className="w-4 h-4 mr-2" />
            Daily Reports ({dailyReports.length})
          </Button>
        </div>
      </div>

      {activeTab === 'notifications' && (
        <div className="space-y-4">
          {notifications.length === 0 ? (
            <Card className="p-8 text-center">
              <Bell className="w-12 h-12 text-gray-400 mx-auto mb-4" />
              <h3 className="text-lg font-semibold text-gray-600 mb-2">No notifications</h3>
              <p className="text-gray-500">All caught up with global intelligence!</p>
            </Card>
          ) : (
            notifications.map(notification => (
              <NotificationItem
                key={notification.id}
                notification={notification}
                onMarkAsRead={markAsRead}
                onDelete={deleteNotification}
              />
            ))
          )}
        </div>
      )}

      {activeTab === 'news' && (
        <div>
          <div className="flex flex-wrap gap-4 mb-6">
            <Select value={newsFilters.category} onValueChange={(value) => setNewsFilters(prev => ({ ...prev, category: value }))}>
              <SelectTrigger className="w-40">
                <SelectValue placeholder="Category" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="">All Categories</SelectItem>
                <SelectItem value="politics">Politics</SelectItem>
                <SelectItem value="economy">Economy</SelectItem>
                <SelectItem value="technology">Technology</SelectItem>
                <SelectItem value="health">Health</SelectItem>
                <SelectItem value="breaking">Breaking</SelectItem>
              </SelectContent>
            </Select>

            <Select value={newsFilters.importance} onValueChange={(value) => setNewsFilters(prev => ({ ...prev, importance: value }))}>
              <SelectTrigger className="w-40">
                <SelectValue placeholder="Importance" />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="">All Levels</SelectItem>
                <SelectItem value="critical">Critical</SelectItem>
                <SelectItem value="high">High</SelectItem>
                <SelectItem value="medium">Medium</SelectItem>
                <SelectItem value="low">Low</SelectItem>
              </SelectContent>
            </Select>

            <Input
              placeholder="Filter by country..."
              value={newsFilters.country}
              onChange={(e) => setNewsFilters(prev => ({ ...prev, country: e.target.value }))}
              className="w-40"
            />
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {filteredNews.map(newsItem => (
              <GlobalNewsCard
                key={newsItem.id}
                newsItem={newsItem}
                onViewDetails={setSelectedNewsItem}
              />
            ))}
          </div>
        </div>
      )}

      {activeTab === 'reports' && (
        <div>
          <div className="flex flex-wrap gap-2 mb-6">
            <Button onClick={() => handleGenerateReport('global', 'Global')}>
              Generate Global Report
            </Button>
            <Button onClick={() => handleGenerateReport('continent', 'Europe')}>
              Generate Europe Report
            </Button>
            <Button onClick={() => handleGenerateReport('country', 'United States')}>
              Generate US Report
            </Button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
            {recentReports.map(report => (
              <DailyReportCard
                key={report.id}
                report={report}
                onViewReport={setSelectedReport}
              />
            ))}
          </div>
        </div>
      )}

      {/* Modals for detailed views would go here */}
      {selectedNewsItem && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4">
          <Card className="max-w-2xl w-full max-h-96 overflow-y-auto">
            <div className="p-6">
              <h2 className="text-xl font-bold mb-4">{selectedNewsItem.title}</h2>
              <p className="text-gray-600 mb-4">{selectedNewsItem.content}</p>
              <Button onClick={() => setSelectedNewsItem(null)}>Close</Button>
            </div>
          </Card>
        </div>
      )}

      {selectedReport && (
        <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center p-4">
          <Card className="max-w-4xl w-full max-h-96 overflow-y-auto">
            <div className="p-6">
              <h2 className="text-xl font-bold mb-4">{selectedReport.target} - {selectedReport.frequency.toUpperCase()} Report</h2>
              <p className="text-gray-600 mb-4">{selectedReport.summary}</p>
              <Button onClick={() => setSelectedReport(null)}>Close</Button>
            </div>
          </Card>
        </div>
      )}
    </div>
  );
};

export default GlobalNotificationProvider;