# ensure_build_files.py
import os


# Required files with minimal content
def ensure_file(path, content=""):
    if not os.path.exists(path):
        with open(path, "w") as f:
            f.write(content)
            print(f"✅ Created missing file: {path}")


# Public icon fallback
ensure_file("public/favicon.ico", "")

# NSIS script placeholder
ensure_file("installer/installer.nsh", "; NSIS placeholder")

# License
ensure_file("installer/LICENSE.txt", "MIT License\n\nGenerated by QMOI AI")

# Icon fallback
if not os.path.exists("icon.ico"):
    os.system("python generate_icon.py")
