// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:56Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

// [PRODUCTION_IMPLEMENTED] this file has no remaining production markers
#!/usr/bin/env python3
"""Link-normalization dry-run

Scans repository Markdown files for links and emits a suggestions report
to `.qmoi_validation/link_normalization_report.txt`.

This is a dry-run: no files are modified. Suggestions include:
- removing leading './'
- collapsing '../' using os.path.normpath relative to the markdown file
- a lowercased suggestion (flagged as tentative)

Run with the repo root as cwd. Designed to be safe and conservative.
"""
import os
import re
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = REPO_ROOT / ".qmoi_validation"
OUT_FILE = OUT_DIR / "link_normalization_report.txt"
MD_LINK_RE = re.compile(r"\[([^\]]+)\]\(([^)]+)\)")

SKIP_DIRS = {".git", ".venv", "node_modules", "venv", "__pycache__"}


def collect_md_files(root: Path):
    for p in root.rglob("*.md"):
        if any(part in SKIP_DIRS for part in p.parts):
            continue
        yield p


def analyze_file(md_path: Path):
    rel = md_path.relative_to(REPO_ROOT)
    suggestions = []
    try:
        text = md_path.read_text(encoding="utf-8")
    except Exception:
        return suggestions

    for i, line in enumerate(text.splitlines(), start=1):
        for m in MD_LINK_RE.finditer(line):
            text_label = m.group(1)
            url = m.group(2).strip()
            entry = {"file": str(rel), "line": i, "label": text_label, "url": url, "suggestions": []}

            # only examine non-empty urls
            if not url:
                continue

            # remote http(s) links: propose small normalizations only
            if url.startswith("http://") or url.startswith("https://"):
                s = url.replace("/./", "/")
                if s != url:
                    entry["suggestions"].append({"why": "collapse './' in url path", "suggested": s})
                # trailing slash suggestion
                if url.endswith("/"):
                    entry["suggestions"].append({"why": "remove trailing slash", "suggested": url.rstrip('/')})
            else:
                # filesystem-relative link — compute safe normalizations
                # 1) remove leading './'
                if url.startswith("./"):
                    s1 = url[2:]
                    entry["suggestions"].append({"why": "remove leading ./", "suggested": s1})

                # 2) collapse ../ and ./ relative to the markdown file
                candidate = (md_path.parent / url).resolve()
                try:
                    rel_to_repo = os.path.relpath(candidate, REPO_ROOT)
                except Exception:
                    rel_to_repo = str(candidate)

                norm = os.path.normpath(os.path.join(md_path.parent, url))
                norm_path = Path(norm).resolve()
                exists = norm_path.exists()
                entry["suggestions"].append({
                    "why": "collapse ../ and normalize relative path",
                    "suggested": rel_to_repo,
                    "exists": exists,
                })

                # 3) lowercased suggestion (tentative)
                if any(c.isupper() for c in url):
                    lc = url.lower()
                    entry["suggestions"].append({"why": "lowercase path (tentative)", "suggested": lc})

            suggestions.append(entry)

    return suggestions


def run():
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    all_suggestions = []
    for md in collect_md_files(REPO_ROOT):
        s = analyze_file(md)
        if s:
            all_suggestions.extend(s)

    with OUT_FILE.open("w", encoding="utf-8") as f:
        f.write("Link Normalization Dry-run Report\n")
        f.write("Generated by scripts/link_normalization_dryrun.py\n\n")
        if not all_suggestions:
            f.write("No markdown links found that need normalization suggestions.\n")
            return 0

        for e in all_suggestions:
            f.write(f"File: {e['file']}\n")
            f.write(f" Line: {e['line']}\n")
            f.write(f" Label: {e['label']}\n")
            f.write(f" Original URL: {e['url']}\n")
            for s in e['suggestions']:
                exists = ''
                if isinstance(s, dict) and s.get('exists') is not None:
                    exists = ' (exists)' if s.get('exists') else ' (does-not-exist)'
                f.write(f"  - Suggestion: {s.get('suggested')} -- {s.get('why')}{exists}\n")
            f.write("\n")

    print(f"Wrote report to {OUT_FILE}")
    return 0


if __name__ == '__main__':
    raise SystemExit(run())
