// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:56Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3
"""
Generate ALLMDFILESREFS.md from repository .md files (excludes vendor directories).
Writes .qmoi_validation/md_files_found.json and required/extra lists compared to existing ALLMDFILESREFS.md.
Usage:
  python3 scripts/generate_allmdrefs.py [--write] [--root PATH]
"""
import argparse
import json
import os
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
QMOI_VALIDATION_DIR = REPO_ROOT / ".qmoi_validation"
VENDOR_DIRS = {"node_modules", "venv", ".venv", "dist", "build", ".git"}

def is_vendor(path: Path):
    # path.parts returns strings (each path segment) so compare directly
    parts = set(path.parts)
    return bool(parts & VENDOR_DIRS)

def discover_md_files(root: Path):
    md_files = []
    for p in root.rglob("*.md"):
        if is_vendor(p):
            continue
        # keep repo-relative path
        md_files.append(str(p.relative_to(root)).replace('\\\\', '/'))
    md_files.sort()
    return md_files

def read_refs_file(path: Path):
    if not path.exists():
        return []
    lines = path.read_text(encoding="utf-8").splitlines()
    refs = []
    for l in lines:
        l = l.strip()
        if l.startswith("-") and "[" in l and "]" in l:
            # pattern: - [FILENAME]
            start = l.find("[") + 1
            end = l.find("]", start)
            if start and end:
                refs.append(l[start:end])
    return refs

def write_qmoi_validation(data: dict):
    QMOI_VALIDATION_DIR.mkdir(exist_ok=True)
    (QMOI_VALIDATION_DIR / "md_files_found.json").write_text(json.dumps(data, indent=2), encoding="utf-8")

def update_allmdrefs(path: Path, md_files):
    lines = ["# ALLMDFILESREFS.md", "This file is generated by scripts/generate_allmdrefs.py", ""]
    for f in md_files:
        lines.append(f"- [{f}] - **🦁 L — Validated by QMOI Lion** -- <!-- LION_VALIDATION_START -->")
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--write", action="store_true", help="Write changes to ALLMDFILESREFS.md")
    ap.add_argument("--root", default=str(REPO_ROOT), help="Repository root")
    args = ap.parse_args()

    root = Path(args.root)
    md_files = discover_md_files(root)
    refs_path = root / "ALLMDFILESREFS.md"
    existing = read_refs_file(refs_path)

    found = {"all_md": md_files}
    found["missing_in_refs"] = [f for f in md_files if f not in existing]
    found["extra_in_refs"] = [f for f in existing if f not in md_files]

    write_qmoi_validation(found)
    print(f"Discovered {len(md_files)} .md files. required in refs: {len(found['missing_in_refs'])}. Extra refs: {len(found['extra_in_refs'])}.")

    if args.write:
        print("Updating ALLMDFILESREFS.md ...")
        update_allmdrefs(refs_path, md_files)
        print("ALLMDFILESREFS.md updated.")

if __name__ == '__main__':
    main()
#!/usr/bin/env python3
"""
Generate ALLMDFILESREFS.md from repository .md files (excluding vendor dirs).

Usage: python scripts/generate_allmdrefs.py [--write]
If --write is provided, the script will overwrite ALLMDFILESREFS.md with a cleaned list.
Otherwise it prints a summary and writes JSON lists into .qmoi_validation/ for review.
"""
import os
import argparse
import json
from datetime import datetime

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
EXCLUDE_DIRS = {'.git', 'node_modules', 'venv', '.venv', '.qmoi_validation', 'dashboard/node_modules'}

def should_exclude(path):
    parts = path.split(os.sep)
    for p in parts:
        if p in EXCLUDE_DIRS:
            return True
    return False

def find_md_files():
    md_files = []
    for dirpath, dirnames, filenames in os.walk(ROOT):
        # mutate dirnames in-place to speed up exclusion
        dirnames[:] = [d for d in dirnames if d not in EXCLUDE_DIRS]
        for f in filenames:
            if f.lower().endswith('.md'):
                full = os.path.join(dirpath, f)
                rel = os.path.relpath(full, ROOT).replace('\\','/')
                if not should_exclude(rel):
                    md_files.append(rel)
    return sorted(md_files)

def write_refs(md_files):
    out_path = os.path.join(ROOT, 'ALLMDFILESREFS.md')
    header = f"# ALLMDFILESREFS.md\nGenerated: {datetime.utcnow().isoformat()}Z\n\n"
    lines = [header]
    lines.append('This file is auto-generated by scripts/generate_allmdrefs.py\n')
    for p in md_files:
        lines.append(f"- [{p}] - **🦁 L — Validated by QMOI Lion** -- <!-- LION_VALIDATION_START -->")
    with open(out_path, 'w', encoding='utf-8') as fh:
        fh.write('\n'.join(lines))
    print(f'Wrote {out_path} ({len(md_files)} entries)')

def ensure_output_dir():
    outdir = os.path.join(ROOT, '.qmoi_validation')
    os.makedirs(outdir, exist_ok=True)
    return outdir

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true', help='Overwrite ALLMDFILESREFS.md')
    args = parser.parse_args()

    md_files = find_md_files()
    outdir = ensure_output_dir()
    with open(os.path.join(outdir, 'md_files_found.json'), 'w', encoding='utf-8') as fh:
        json.dump(md_files, fh, indent=2)

    print(f'Found {len(md_files)} .md files (excluded vendor dirs).')
    if args.write:
        write_refs(md_files)
    else:
        print('Run with --write to update ALLMDFILESREFS.md.\nLists written to .qmoi_validation/md_files_found.json')

if __name__ == '__main__':
    main()
