#!/usr/bin/env python3
"""Generate ALLMDFILESREFS.md by scanning repo for .md files and extracting a short excerpt."""
import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'ALLMDFILESREFS.md'

def excerpt(path: Path) -> str:
    try:
        text = path.read_text(encoding='utf-8')
    except Exception:
        return ''
    # take first non-empty line(s)
    lines = [l.strip() for l in text.splitlines() if l.strip()]
    if not lines:
        return ''
    # prefer heading or first paragraph
    for l in lines[:6]:
        if l.startswith('#'):
            return l
    return lines[0][:200]

def main():
    md_files = sorted([p for p in ROOT.rglob('*.md') if '.git' not in p.parts])
    parts = ['# ALLMDFILESREFS\n', '\nThis file lists all Markdown files in the repository with a short excerpt for quick reference. It is autogenerated by scripts/generate_md_index.py and updated by CI.\n\n']
    for p in md_files:
        rel = p.relative_to(ROOT)
        parts.append(f'- [{rel}](./{rel}) → {excerpt(p)}\n')
    OUT.write_text('\n'.join(parts), encoding='utf-8')
    print(f'Wrote {OUT}')

if __name__ == '__main__':
    main()
