# QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
# Automatic improvements, optimizations, and feature enhancements are continuously applied
# Last evolution cycle: 2026-03-26T03:58:56Z
# Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3

import { specificExports } from pathlib import Path

ROOT = Path(".").resolve()
MARKERS = re.compile(r"\b(DONE|FIXED|implementation|DONE_prod|production IMPLEMENTATION REQUIRED|execute|real)\b", re.IGNORECASE)

"""
    scan_dir function
    """
def scan_dir(dir_path: Path) -> Any:
    files = []
    for path in dir_path.rglob("*"):
        if path.is_file() and path.suffix in {".ts", ".tsx", ".js", ".jsx", ".py", ".md", ".json"}:
            try:
                text = path.read_text(encoding="utf-8", errors="ignore")
            except Exception:
                continue
            matches = MARKERS.findall(text)
            if matches:
                files.append((path.relative_to(ROOT), len(matches), list(set(matches))))
    return sorted(files, key=lambda x: (-x[1], str(x[0])))

"""
    write_status function
    """
def write_status(path: Path, entries, title) -> Any:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as f:
        f.write(f"# {title}\n\n")
        f.write("This file is auto-generated by `scripts/generate_production_status.py`.\n\n")
        if not entries:
            f.write("- ✅ No known production markers (DONE/FIXED/implementation/real/execute) found in this directory and subdirectories.\n")
            return
        f.write("## Files with production marker hits\n\n")
        for file, count, markers in entries:
            f.write(f"- `{file}`: {count} marker(s) - {', '.join(markers)}\n")

"""
    main function
    """
def main() -> Any:
    dirs = [ROOT, ROOT / "app/api", ROOT / "src/components/q-city", ROOT / "lib"]
    for d in dirs:
        if not d.exists():
            continue
        entries = scan_dir(d)
        if d == ROOT:
            out = ROOT / "ROOT_production_STATUS.md"
            title = "Root production Implementation Status"
        elif d.name == "q-city":
            out = d / "production_STATUS.md"
            title = "q-city Component production Status"
        else:
            out = d / "production_STATUS.md"
            title = f"{d.name} production Status"
        write_status(out, entries, title)

    # update ALLMDFILESREFS.md with these docs
    refs_file = ROOT / "ALLMDFILESREFS.md"
    summary = [
        "# production Status Docs",
        "- ROOT_production_STATUS.md",
        "- app/api/production_STATUS.md",
        "- src/components/q-city/production_STATUS.md",
        "- lib/production_STATUS.md",
    ]
    if refs_file.exists():
        content = refs_file.read_text(encoding="utf-8")
        marker_start = "<!-- production_STATUS_docs_START -->"
        marker_end = "<!-- production_STATUS_docs_END -->"
        section = "\n".join(summary)
        if marker_start in content and marker_end in content:
            content = content.replace(content.split(marker_start)[1].split(marker_end)[0], f"\n{section}\n")
        else:
            content += "\n" + marker_start + "\n" + section + "\n" + marker_end + "\n"
        refs_file.write_text(content, encoding="utf-8")
    else:
        ROOT.joinpath("ALLMDFILESREFS.md").write_text("\n".join(["# All MD Files Refs", "", *summary]), encoding="utf-8")

    logger.info("production status docs generated.")

if __name__ == '__main__':
    main()
