#!/usr/bin/env python3
"""
Generate ALLMDFILESREFS.md from repository .md files (excluding vendor directories).

Usage:
  python3 scripts/generate_allmdrefs.py [--write] [--root PATH]
"""

import argparse
import json
import logging
from pathlib import Path
from datetime import datetime

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

REPO_ROOT = Path(__file__).resolve().parent.parent
EXCLUDE_DIRS = {'.git', 'node_modules', 'venv', '.venv', '.qmoi_validation'}


def should_exclude(path: Path) -> bool:
    return any(part in EXCLUDE_DIRS for part in path.parts)


def discover_md_files(root: Path) -> list[str]:
    md_files = []
    for path in sorted(root.rglob('*.md')):
        if should_exclude(path):
            continue
        md_files.append(path.relative_to(root).as_posix())
    return md_files


def write_qmoi_validation(data: dict) -> None:
    validation_dir = REPO_ROOT / '.qmoi_validation'
    validation_dir.mkdir(exist_ok=True)
    (validation_dir / 'md_files_found.json').write_text(json.dumps(data, indent=2), encoding='utf-8')


def update_allmdrefs(path: Path, md_files: list[str]) -> None:
    header = [
        '# ALLMDFILESREFS.md',
        f'Generated: {datetime.utcnow().isoformat()}Z',
        '',
        'This file is generated by scripts/generate_allmdrefs.py',
        ''
    ]
    lines = header + [f'- [{f}] - **🦁 L — Validated by QMOI Lion** -- <!-- LION_VALIDATION_START -->' for f in md_files]
    path.write_text('\n'.join(lines) + '\n', encoding='utf-8')


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument('--write', action='store_true', help='Overwrite ALLMDFILESREFS.md')
    parser.add_argument('--root', default=str(REPO_ROOT), help='Repository root')
    args = parser.parse_args()

    root = Path(args.root)
    md_files = discover_md_files(root)
    refs_path = root / 'ALLMDFILESREFS.md'
    existing = []
    if refs_path.exists():
        lines = refs_path.read_text(encoding='utf-8').splitlines()
        for line in lines:
            line = line.strip()
            if line.startswith('- [') and ']' in line:
                start = line.find('[') + 1
                end = line.find(']', start)
                if start and end:
                    existing.append(line[start:end])

    result = {
        'all_md': md_files,
        'missing_in_refs': [f for f in md_files if f not in existing],
        'extra_in_refs': [f for f in existing if f not in md_files]
    }
    write_qmoi_validation(result)
    logger.info(f'Discovered {len(md_files)} .md files. Missing refs: {len(result["missing_in_refs"])}. Extra refs: {len(result["extra_in_refs"])}.')

    if args.write:
        logger.info('Updating ALLMDFILESREFS.md ...')
        update_allmdrefs(refs_path, md_files)
        logger.info('ALLMDFILESREFS.md updated.')


if __name__ == '__main__':
    main()
