module.exports = {
  apps: [
    {
      name: "qmoi-app",
      script: "./node_modules/.bin/next",
      args: "start",
      cwd: "/workspaces/qmoi-enhanced",
      watch: false,
      autorestart: true,
      max_memory_restart: "512M",
      env: { NODE_ENV: "production", PORT: 3000 },
      error_file: "logs/app-error.log",
      out_file: "logs/app-out.log",
    },
    {
      name: "qmoi-health",
      script: "scripts/qmoi-production-autohealth.js",
      cwd: "/workspaces/qmoi-enhanced",
      watch: false,
      autorestart: true,
      max_memory_restart: "300M",
      env: { NODE_ENV: "production" },
      error_file: "logs/health-error.log",
      out_file: "logs/health-out.log",
    },
    {
      name: "qmoi-dashboard",
      script: "node",
      args: "-e \"logger.info('Dashboard'); setInterval(()=>{}, 1000)\"",
      cwd: "/workspaces/qmoi-enhanced",
      watch: false,
      autorestart: true,
      env: { NODE_ENV: "production", PORT: 3001 },
      error_file: "logs/dashboard-error.log",
      out_file: "logs/dashboard-out.log",
    },
  ],
};
