// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:52Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3

"""
Auto-fix helper (DRY-RUN) for implementation matches.

This tool reads `matches.json` (generated by `find_placeholders.py`) and prepares
safe, reversible edits in a patch file `placeholder_fixes.patch`.

It does NOT apply changes by default. Instead it creates a unified diff that
can be reviewed and applied manually (or by this script with --apply).

Safe edits performed (configurable):
- Replace function bodies that only contain `pass` and have implementation markers
  with `raise NotImplementedError('production implementation required: <reason>')`.

This script is conservative and intended to reduce accidental destructive edits.
"""
import json
from pathlib import Path
import argparse
import difflib
import re

ROOT = Path(__file__).resolve().parents[1]
MATCHES = ROOT / 'matches.json'
PATCH_OUT = ROOT / 'placeholder_fixes.patch'

def load_matches():
    if not MATCHES.exists():
        print('No matches.json found. Run tools/find_placeholders.py first.')
        return []
    return json.loads(MATCHES.read_text(encoding='utf-8'))

def produce_edits(matches):
    # Group matches by file
    by_file = {}
    for m in matches:
        by_file.setdefault(m['file'], []).append(m)

    edits = {}
    for rel, entries in by_file.items():
        p = ROOT / rel
        try:
            original = p.read_text(encoding='utf-8')
        except Exception:
            continue
        lines = original.splitlines(keepends=True)
        changed = False
        # simple heuristic: if a function contains 'pass' and nearby DONE/FIXED, replace pass
        for e in entries:
            ln = e['line'] - 1
            window_start = max(0, ln-5)
            window_end = min(len(lines), ln+5)
            window = ''.join(lines[window_start:window_end])
            if re.search(r"\bpass\b", window) and re.search(r"DONE|FIXED|implementation|REPLACE_ME|production|prod only|not for production|real", window, re.I):
                # find the 'pass' line index and replace that line
                for i in range(window_start, window_end):
                    if re.search(r"^\s*pass\s*(#.*)?$", lines[i]):
                        indent = re.match(r"^(\s*)", lines[i]).group(1)
                        reason = e.get('snippet', '').strip()[:120]
                        replacement = indent + "raise NotImplementedError('production implementation required: " + reason.replace("'","\\'") + "')\n"
                        lines[i] = replacement
                        changed = True
                        break
        if changed:
            new = ''.join(lines)
            edits[rel] = (original, new)
    return edits

def write_patch(edits):
    parts = []
    for rel, (orig, new) in edits.items():
        orig_lines = orig.splitlines(keepends=True)
        new_lines = new.splitlines(keepends=True)
        diff = difflib.unified_diff(orig_lines, new_lines, fromfile=rel, tofile=rel + ' (proposed)', lineterm='')
        parts.extend(diff)
    if parts:
        PATCH_OUT.write_text('\n'.join(parts), encoding='utf-8')
        print(f'Wrote patch to {PATCH_OUT}')
    else:
        print('No safe edits proposed.')

def apply_patch():
    # intentionally left as a manual step; apply with git apply or similar
    print('To apply the patch run: git apply --index placeholder_fixes.patch')

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('--apply', action='store_true', help='Show apply instructions (does not auto-commit)')
    args = parser.parse_args()

    matches = load_matches()
    if not matches:
        return
    edits = produce_edits(matches)
    write_patch(edits)
    if args.apply:
        apply_patch()

if __name__ == '__main__':
    main()
