// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:52Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3

"""
Autotest runner for repository health checks and conservative test execution.

This script runs a sequence of safe checks, writes a human-readable report to
`tools/autotest_report.md` and produces machine-readable outputs for automation
(`tools/jest_list.txt`, `tools/jest_results.json`). It will only run the
full Jest suite if the dry-list of tests is within a reasonable size.

Behavior (safe defaults):
- Run implementation scanner, auto-fix dry-run, md refs regen, versions and link checks
- produce `tools/jest_list.txt` (list of test files)
- If test count <= 2000, run Jest with JSON output and coverage to
  `tools/jest_results.json` (adjust threshold as needed)
"""

from pathlib import Path
import subprocess
import json
import sys
import shlex

ROOT = Path(__file__).resolve().parents[1]
TOOLS = ROOT / 'tools'
REPORT_MD = TOOLS / 'autotest_report.md'
JEST_LIST = TOOLS / 'jest_list.txt'
JEST_RESULTS = TOOLS / 'jest_results.json'

def run_cmd(cmd, cwd=ROOT):
    print(f'> {cmd}')
    res = subprocess.run(cmd, shell=True, capture_output=True, text=True, cwd=str(cwd))
    out = (res.stdout or '') + (res.stderr or '')
    return res.returncode, out

def find_jest_bin():
    """Return list of candidate jest commands (prefer local binary).

    We'll try each in sequence until one works. The caller should attempt
    to run listTests using each candidate and pick the first that succeeds.
    """
    candidates = []
    local = ROOT / 'node_modules' / '.bin' / 'jest'
    if local.exists():
        candidates.append(str(local))
    # prefer npm exec (if available), then npx, then yarn
    candidates.append('npm exec --no-install jest')
    candidates.append('npx jest')
    candidates.append('yarn jest')
    return candidates

def safe_write(path: Path, text: str):
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding='utf-8')

def main():
    report = []
    report.append('# Autotest Report')
    report.append('Generated by tools/autotest_runner.py')

    # Steps: scanners and comprehensive validations
    steps = [
        ('implementation scan', 'python3 tools/find_real implementations.py'),
        ('auto-fix dry-run', 'python3 tools/auto_fix_real implementations.py'),
        ('qmoi lint', 'python3 tools/qmoi_lint.py'),
        ('regen md refs', 'python3 tools/update_all_md_refs.py'),
        ('collect versions', 'python3 tools/collect_versions.py'),
        ('check links', 'python3 tools/check_links.py'),
    ]

    for name, cmd in steps:
        rc, out = run_cmd(cmd)
        ok = (rc == 0)
        report.append(f'## {name} (rc={rc})')
        report.append('```')
        report.append(out.strip())
        report.append('```')

    # Run priority scan to focus on source files
    report.append('\n## Step — Priority scan (focus on source files)')
    rc, out = run_cmd('python3 tools/priority_scan.py')
    report.append(f'priority_scan rc={rc}')
    report.append('```')
    report.append(out.strip())
    report.append('```')

    # Run generator for conservative suggested fixes (dry-run)
    report.append('\n## Step — Generate conservative fix templates (dry-run)')
    rc, out = run_cmd('python3 tools/generate_fix_templates.py')
    report.append(f'generate_fix_templates rc={rc}')
    report.append('```')
    report.append(out.strip())
    report.append('```')

    # Run pytest for Python tests
    report.append('\n## Step — Run Python tests (pytest)')
    try:
        import pytest
        rc, out = run_cmd('python3 -m pytest --tb=short --maxfail=5 -q')
        report.append(f'pytest rc={rc}')
    except ImportError:
        rc, out = 1, 'pytest not installed - install with: pip install pytest'
        report.append(f'pytest rc={rc} (not installed)')
    report.append('```')
    report.append(out.strip())
    report.append('```')

    # Run Cypress E2E tests
    report.append('\n## Step — Run E2E tests (Cypress)')
    if run_cmd('which npm')[0] == 0:
        rc, out = run_cmd('npm run e2e:run')
        report.append(f'cypress rc={rc}')
    else:
        rc, out = 1, 'npm not found - Node.js not installed'
        report.append(f'cypress rc={rc} (npm not available)')
    report.append('```')
    report.append(out.strip())
    report.append('```')

    # Jest: dry-list tests first
    jest_candidates = find_jest_bin()
    report.append('Tried jest command candidates:')
    list_out = None
    used_cmd = None
    last_out = ''
    for cand in jest_candidates:
        report.append(f'- trying: {cand} --listTests')
        rc, out = run_cmd(f"{cand} --listTests")
        last_out = out
        if rc == 0:
            list_out = out
            used_cmd = cand
            report.append(f'-> succeeded with: {cand}')
            break
        else:
            report.append(f'-> failed (rc={rc})')

    if list_out is None:
        report.append('## Jest listTests failed for all candidates - Jest/Node.js not installed')
        report.append('```')
        # include last captured output if any
        report.append(last_out.strip() if last_out else 'no output')
        report.append('```')
        safe_write(REPORT_MD, '\n'.join(report))
        print(f'Wrote {REPORT_MD}')
        return

    # write list
    test_lines = [line.strip() for line in list_out.splitlines() if line.strip()]
    safe_write(JEST_LIST, '\n'.join(test_lines))
    report.append(f'- Jest tests found: {len(test_lines)} (listed in {JEST_LIST})')

    # Conservative threshold to avoid running enormous test suites here
    MAX_TESTS = 2000
    if len(test_lines) > MAX_TESTS:
        report.append(f'== SKIPPING full Jest run: {len(test_lines)} tests > {MAX_TESTS} threshold')
        safe_write(REPORT_MD, '\n'.join(report))
        print(f'Wrote {REPORT_MD}')
        return

    # Run jest with JSON output and coverage
    jest_output_path = JEST_RESULTS
    # use the successful candidate command
    jest_cmd = f'{used_cmd} --json --outputFile="{str(jest_output_path)}" --coverage --maxWorkers=50% --silent'
    rc, out = run_cmd(jest_cmd)
    report.append(f'## Jest run (rc={rc})')
    report.append('```')
    report.append(out.strip())
    report.append('```')

    # If jest wrote the JSON results, try to read and summarize
    if jest_output_path.exists():
        try:
            jr = json.loads(jest_output_path.read_text(encoding='utf-8'))
            summary = {
                'numTotalTests': jr.get('numTotalTests'),
                'numPassedTests': jr.get('numPassedTests'),
                'numFailedTests': jr.get('numFailedTests'),
                'numPendingTests': jr.get('numPendingTests'),
                'numTotalTestSuites': jr.get('numTotalTestSuites')
            }
            report.append('## Jest summary')
            report.append(json.dumps(summary, indent=2))
        except Exception as e:
            report.append(f'- Failed to parse jest results JSON: {e}')
    else:
        report.append('- jest results JSON not found')

    # Finalize report
    safe_write(REPORT_MD, '\n'.join(report))
    print(f'Wrote {REPORT_MD}')

if __name__ == '__main__':
    main()
