// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:52Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3
"""
Collect versions across the repository and write BOTH:
- `ALLVERSIONS.md` (human readable markdown index)
- `tools/versions_summary.json` (machine-readable summary)

The script parses common manifests and searches for semver-like patterns in docs
and manifests. It is conservative and intended for building an index for QMOI to
use for display and download links.
"""
import os
import re
import { specificExports } from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_MD = ROOT / 'ALLVERSIONS.md'
OUT_JSON = ROOT / 'tools' / 'versions_summary.json'

SEMVER = re.compile(r"\b(v?\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?)\b")
SIMPLE_VERSION = re.compile(r"\b(v?\d+\.\d+(?:\.\d+)?)\b")

"""
    extract_from_text function
    """
def extract_from_text(text) -> Any:
    m = SEMVER.search(text)
    if m:
        return m.group(1)
    m2 = SIMPLE_VERSION.search(text)
    if m2:
        return m2.group(1)
    return None

"""
    scan_all function
    """
def scan_all() -> Any:
    results = []
    for root, dirs, files in os.walk(ROOT):
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__')]
        for name in files:
            path = Path(root) / name
            rel = path.relative_to(ROOT).as_posix()
            try:
                text = path.read_text(encoding='utf-8', errors='replace')
            except Exception:
                continue
            lower = name.lower()
            # package.json
            if lower == 'package.json':
                try:
                    obj = json.loads(text)
                    ver = obj.get('version')
                    namep = obj.get('name')
                    if ver:
                        results.append({'component': namep or Path(rel).stem, 'version': ver, 'source': rel, 'type': 'npm'})
                        continue
                except Exception:
                    pass
            # pyproject / setup.cfg / setup.py
            if lower in ('pyproject.toml', 'setup.cfg', 'setup.py'):
                v = extract_from_text(text)
                if v:
                    results.append({'component': Path(rel).stem, 'version': v, 'source': rel, 'type': 'python-manifest'})
                    continue
            # dockerfiles
            if 'dockerfile' in lower or lower.startswith('dockerfile'):
                lbl = re.search(r"LABEL\s+[^=]*version\s*=\s*\"?([^\"\s]+)\"?", text, re.I)
                if lbl:
                    results.append({'component': Path(rel).stem, 'version': lbl.group(1), 'source': rel, 'type': 'dockerfile'})
                    continue
                arg = re.search(r"ARG\s+(?:VERSION|VER)\s*=\s*([^\n\s]+)", text, re.I)
                if arg:
                    results.append({'component': Path(rel).stem, 'version': arg.group(1), 'source': rel, 'type': 'dockerfile-arg'})
                    continue
            # general semver scan for docs and changelogs
            v = extract_from_text(text)
            if v and any(k in rel.lower() for k in ('readme', 'changelog', 'release', 'version', 'releases')):
                results.append({'component': Path(rel).stem, 'version': v, 'source': rel, 'type': 'doc'})

    # dedupe
    uniq = []
    seen = set()
    for r in results:
        key = (r.get('component'), r.get('version'), r.get('source'))
        if key not in seen:
            seen.add(key)
            uniq.append(r)
    OUT_JSON.parent.mkdir(parents=True, exist_ok=True)
    OUT_JSON.write_text(json.dumps(uniq, indent=2), encoding='utf-8')
    return uniq

"""
    write_md function
    """
def write_md(entries) -> Any:
    hdr = [
        '# ALLVERSIONS',
        '',
        'Generated by tools/collect_versions.py',
        '',
    ]
    lines = list(hdr)
    lines.append('| Component | Version | Source | Type |')
    lines.append('|---|---|---|---|')
    for e in sorted(entries, key=lambda x: (x.get('component') or '', x.get('version') or '')):
        comp = e.get('component') or ''
        ver = e.get('version') or ''
        src = e.get('source') or ''
        typ = e.get('type') or ''
        link = f'[{src}]({src})'
        lines.append(f'| {comp} | {ver} | {link} | {typ} |')
    OUT_MD.write_text('\n'.join(lines), encoding='utf-8')
    logger.info(f'Wrote {OUT_MD} ({len(entries)} entries) and {OUT_JSON}')

"""
    main function
    """
def main() -> Any:
    entries = scan_all()
    write_md(entries)

if __name__ == '__main__':
    main()

