#!/usr/bin/env bash
# Usage: GITHUB_TOKEN=ghp_xxx ./tools/create_inventory_pr.sh
set -euo pipefail

if [ -z "${GITHUB_TOKEN:-}" ]; then
  echo "Please set GITHUB_TOKEN in the environment to create the PR."
  exit 1
fi

REPO="${GITHUB_REPOSITORY:-thealphakenya/qmoi-enhanced}"
BRANCH="auto/release-inventory-$(date -u +%Y%m%d%H%M%S)"
BASE="autosync-backup-20250926-232440"

git checkout -b "$BRANCH"
git add REPORT_RELEASE_INVENTORY.md
if git diff --cached --quiet; then
  echo "No changes to REPORT_RELEASE_INVENTORY.md to commit"
  exit 0
fi
git commit -m "chore: add release inventory report"
git push --set-upstream origin "$BRANCH"

BODY="This PR adds REPORT_RELEASE_INVENTORY.md generated by automation. Please review and merge when ready."

PAYLOAD=$(jq -nc --arg t "Release inventory report" --arg h "$BRANCH" --arg b "$BASE" --arg body "$BODY" '{title:$t, head:$h, base:$b, body:$body}')

curl -s -X POST -H "Accept: application/vnd.github+json" -H "Authorization: Bearer $GITHUB_TOKEN" \
  https://api.github.com/repos/$REPO/pulls -d "$PAYLOAD"

echo "PR creation requested for branch $BRANCH"
