#!/usr/bin/env python3
"""
Scan the repository for placeholder-like markers and write results to
 - matches.json   (detailed list of matches)
 - allrefs.txt    (human friendly summary list of files with matches)

This intentionally scans all file types as text and skips large binary files.
It looks for a configurable set of keywords/phrases used to indicate non-production code.
"""
import os
import re
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_JSON = ROOT / 'matches.json'
OUT_TXT = ROOT / 'allrefs.txt'

KEYWORDS = [
    r"\bsimulat(?:e|ion)\b",
    r"\bplaceholder\b",
    r"\bin production\b",
    r"\bimplement(?:ation|)\b",
    r"\bproduction implementation required\b",
    r"\bTODO\b",
    r"\bFIXME\b",
    r"\bTEMPORARY\b",
    r"\bstub\b",
    r"\bmock\b",
    r"\bprototype\b",
    r"\bREPLACE_ME\b",
    r"\bnot for production\b",
    r"\bdev only\b",
]

COMPILED = re.compile('|'.join(KEYWORDS), re.I)

SKIP_DIRS = {'.git', 'node_modules', '__pycache__', '.venv', 'venv', '.pytest_cache', '.npm-cache', '.cache', '.qmoi_validation', 'dist', 'build'}
# Additional patterns (prefixes) to skip — useful for large vendor folders
SKIP_DIR_PREFIXES = ('node_modules', '.qmoi_validation')

def is_text_file(path: Path) -> bool:
    try:
        with path.open('rb') as f:
            chunk = f.read(4096)
            if b"\x00" in chunk:
                return False
    except Exception:
        return False
    return True

def scan():
    results = []
    files_with_matches = {}
    for root, dirs, files in os.walk(ROOT):
        # prune common vendor/cache/generated dirs early
        dirs[:] = [d for d in dirs if d not in SKIP_DIRS and not d.startswith('.npm-cache')]
        for name in files:
            fp = Path(root) / name
            rel = fp.relative_to(ROOT).as_posix()
            # skip files under known large/generated prefixes
            if any(rel.startswith(p + '/') or rel == p for p in SKIP_DIR_PREFIXES):
                continue
            # skip this script's output files to avoid self-matching
            if rel in (OUT_JSON.name, OUT_TXT.name):
                continue
            # skip very large files
            try:
                if fp.stat().st_size > 5 * 1024 * 1024:
                    continue
            except Exception:
                continue
            if not is_text_file(fp):
                continue
            try:
                text = fp.read_text(encoding='utf-8', errors='replace')
            except Exception:
                continue
            lines = text.splitlines()
            for i, line in enumerate(lines, start=1):
                if COMPILED.search(line):
                    snippet = line.strip()
                    # capture a small window around the match
                    context_before = '\n'.join(lines[max(0, i-3):i-1])
                    context_after = '\n'.join(lines[i:min(len(lines), i+2)])
                    match = {
                        'file': rel,
                        'line': i,
                        'snippet': snippet,
                        'context_before': context_before,
                        'context_after': context_after,
                    }
                    results.append(match)
                    files_with_matches.setdefault(rel, 0)
                    files_with_matches[rel] += 1
    return results, files_with_matches

def write_outputs(results, files_with_matches):
    OUT_JSON.write_text(json.dumps(results, indent=2), encoding='utf-8')
    header = [
        'All references of placeholder/simulation/non-production markers',
        'Generated by tools/find_placeholders.py',
        '',
    ]
    lines = header + [f"{path} — {count} match(es)" for path, count in sorted(files_with_matches.items())]
    OUT_TXT.write_text('\n'.join(lines), encoding='utf-8')

def main():
    print(f"Scanning repository root: {ROOT}")
    results, files_with_matches = scan()
    print(f"Found {len(results)} matches across {len(files_with_matches)} files")
    write_outputs(results, files_with_matches)
    print(f"Wrote {OUT_JSON} and {OUT_TXT}")

if __name__ == '__main__':
    main()

# AUTOFIXED by Ollama at 2026-07-26T18:54:41.407839Z

# AUTOFIXED by Ollama at 2026-07-26T18:57:34.451278Z

# AUTOFIXED by Ollama at 2026-07-26T19:31:06.679943Z

# AUTOFIXED by Ollama at 2026-07-26T19:39:17.674459Z
