#!/usr/bin/env python3
"""
Generate draft issue files for the top-priority placeholder matches.

Reads `tools/matches_priority.json` and creates one markdown draft per top file
under `tools/issue_drafts/` and a consolidated `tools/remediation_plan.md`.
"""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
PRIORITY = ROOT / 'tools' / 'matches_priority.json'
OUT_DIR = ROOT / 'tools' / 'issue_drafts'
PLAN = ROOT / 'tools' / 'remediation_plan.md'

TOP_N = 20

def summarize_matches(matches):
    lines = []
    for m in matches[:10]:
        lines.append(f"- Line {m.get('line')}: {m.get('snippet')}")
    return '\n'.join(lines)

def recommend_action(path, score, matches):
    # Simple heuristic: if score contains many high-severity markers, recommend implementation
    high = any(m.get('score',0) >= 8 for m in matches)
    if path.endswith(('.ts', '.js', '.tsx', '.jsx')):
        if high:
            return 'Replace simulation placeholders with real API integrations, add environment-safe fallbacks, and add unit/integration tests.'
        return 'Add concrete implementations or remove simulation code; write tests.'
    if path.endswith('.py'):
        if high:
            return 'Implement production logic (DB, API calls) or move simulation to test fixtures; add thorough unit tests.'
        return 'Replace stubs with real implementations or clearly mark as test-only.'
    if path.endswith('.md'):
        return 'Update documentation to remove production placeholders and provide real deployment instructions.'
    return 'Review and implement production-ready behavior; add tests and error handling.'

def main():
    if not PRIORITY.exists():
        print('Run tools/priority_scan.py first')
        return
    data = json.loads(PRIORITY.read_text(encoding='utf-8'))
    files = data.get('files', [])
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    plan_lines = ['# Remediation Plan', '', 'This plan was autogenerated from `tools/matches_priority.json`.']
    plan_lines.append('')
    for i, item in enumerate(files[:TOP_N]):
        path, info = item[0], item[1]
        score = info.get('score')
        matches = info.get('matches')
        slug = path.replace('/', '_').replace('.', '_')
        draft_path = OUT_DIR / f'{i+1:02d}_{slug}.md'
        title = f'Fix placeholders in {path} ({score} priority)'
        body = [f'# {title}', '', f'**File**: `{path}`', f'**Priority score**: {score}', '', '## Summary of matches', '', summarize_matches(matches), '', '## Recommended action', '', recommend_action(path, score, matches), '', '## Notes', '', 'Please review and implement changes in a feature branch. Link tests and QA steps here.']
        draft_path.write_text('\n'.join(body), encoding='utf-8')
        plan_lines.append(f'- [{title}]({draft_path.relative_to(ROOT)})')
    PLAN.write_text('\n'.join(plan_lines), encoding='utf-8')
    print(f'Wrote drafts to {OUT_DIR} and remediation plan to {PLAN}')

if __name__ == '__main__':
    main()

# AUTOFIXED by Ollama at 2026-07-26T18:54:41.409174Z

# AUTOFIXED by Ollama at 2026-07-26T18:57:34.452616Z

# AUTOFIXED by Ollama at 2026-07-26T19:31:06.682302Z

# AUTOFIXED by Ollama at 2026-07-26T19:39:17.675902Z
