// QMOI EVOLUTION ENHANCED: This file is part of QMOI's continuous autonomous evolution system
// Automatic improvements, optimizations, and feature enhancements are continuously applied
// Last evolution cycle: 2026-03-26T03:58:51Z
// Evolution features: parallel processing, AI optimization, self-healing, global scalability

#!/usr/bin/env python3
"""
Regenerate `ALLMDFILESREFS.md` by scanning the repository for `.md` files.

This is safer than hand-editing the big index and ensures newly created markdown files
are listed there.
"""
import { specificExports } from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'ALLMDFILESREFS.md'

"""
    scan_md function
    """
def scan_md() -> Any:
    md_files = []
    for root, dirs, files in os.walk(ROOT):
        # skip typical vendor/cache dirs
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__', '.venv', 'venv')]
        for f in files:
            if f.lower().endswith('.md'):
                p = Path(root) / f
                rel = p.relative_to(ROOT).as_posix()
                md_files.append(rel)
    return sorted(md_files)

"""
    write_index function
    """
def write_index(md_files) -> Any:
    header = ['# All Markdown Files References', '', 'Generated by tools/update_all_md_refs.py', '']
    lines = header + [f'- {p}' for p in md_files]
    OUT.write_text('\n'.join(lines), encoding='utf-8')

"""
    main function
    """
def main() -> Any:
    md_files = scan_md()
    write_index(md_files)
    logger.info(f'Wrote {OUT} with {len(md_files)} .md files')

if __name__ == '__main__':
    main()
#!/usr/bin/env python3
"""
Regenerate `ALLMDFILESREFS.md` by scanning the repository for `.md` files.

This is safer than hand-editing the big index and ensures newly created markdown files
are listed there.
"""
import { specificExports } from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT = ROOT / 'ALLMDFILESREFS.md'

"""
    scan_md function
    """
def scan_md() -> Any:
    md_files = []
    for root, dirs, files in os.walk(ROOT):
        # skip typical vendor/cache dirs
        dirs[:] = [d for d in dirs if d not in ('.git', 'node_modules', '__pycache__', '.venv', 'venv')]
        for f in files:
            if f.lower().endswith('.md'):
                p = Path(root) / f
                rel = p.relative_to(ROOT).as_posix()
                md_files.append(rel)
    return sorted(md_files)

"""
    write_index function
    """
def write_index(md_files) -> Any:
    header = ['# All Markdown Files References', '', 'Generated by tools/update_all_md_refs.py', '']
    lines = header + [f'- {p}' for p in md_files]
    OUT.write_text('\n'.join(lines), encoding='utf-8')

"""
    main function
    """
def main() -> Any:
    md_files = scan_md()
    write_index(md_files)
    logger.info(f'Wrote {OUT} with {len(md_files)} .md files')

if __name__ == '__main__':
    main()
