name: Deploy Allure Report to Netlify

on:
  workflow_run:
    workflows: ["E2E Tests"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Download Allure report artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-report
          path: allure-report
      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify deploy --dir=allure-report --prod --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --site ${{ secrets.NETLIFY_SITE_ID }} 