name: Auto-merge automated PRs

on:
  pull_request:
    types: [opened, labeled, synchronize, reopened]

jobs:
  auto-merge:
    runs-on: ubuntu-latest
    if: github.actor == 'github-actions[bot]' || contains(github.event.pull_request.title, 'Automated Fix') || contains(github.event.pull_request.user.login, 'dependabot')
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Wait for checks
        uses: actions/github-script@v6
        with:
          script: |
            const pr = context.payload.pull_request;
            const { owner, repo } = context.repo;
            const checks = await github.rest.checks.listForRef({ owner, repo, ref: pr.head.sha });
            core.info(`Found ${checks.data.total_count} check runs`);
            return;

      - name: Merge if checks passed
        uses: pascalgn/automerge-action@v0.14.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          merge_method: squash
          status: success
          label: automerge
