name: CI

on:
  push:
    branches: ["**"]
  pull_request:
    branches: ["**"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Validate environment
        run: |
          node scripts/validate-env.cjs || echo "Env validation failed (expected in CI to set secrets)."

      - name: Install dependencies
        run: npm ci

      - name: Run local CI helper (auto-fix & tests)
        run: npm run ci:local || true

      - name: Lint
        run: npm run lint || true

      - name: Unit tests (MPesa adapter)
        run: npm run test:unit || true

      - name: NPM Audit (moderate)
        run: npm audit --audit-level=moderate || true

      - name: Upload test results (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-results
          path: test-results || ./
      - name: Upload build artifacts if present
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: qmoi-build-artifacts
          path: Qmoi_apps/**
name: CI Pipeline
'on':
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
permissions:
  contents: write
  pull-requests: write
jobs:
  build-and-test:
    name: Build, Test, Fix, and Report
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 18.x
          - 20.x
          - 22.x
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Auto-fix errors
        run: |
          npm run fix:all || echo "Auto-fix attempted."
          python scripts/auto_updater.py || echo "Python auto-fix attempted."
      - name: Error summary
        run: |
          echo "If errors occurred, see logs above. All auto-fix steps have been attempted."
      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: npm
      - name: Install dependencies
        run: npm install
      - name: Run all tests
        run: npm run test:all
      - name: Run fix test
        run: npm run fix:test
      - name: Run autotest after fix
        run: npm run autotest:all
      - name: Check linting and formatting
        run: |
          echo "Checking linting and formatting..."
          npm run lint --if-present || echo "No lint script found"
          npm run format:check --if-present || echo "No format check script found"
      - name: Generate coverage
        run: |
          if npm run coverage --if-present; then
            echo "Coverage generated."
          else
            echo "No coverage script found, skipping."
          fi
      - name: Upload coverage to Codecov
        if: success()
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./coverage/**/*.xml, ./coverage/**/*.json, ./coverage/**/*.lcov
          fail_ci_if_error: false
          verbose: false
      - name: Create Pull Request
        if: github.event_name == 'push' && success() && matrix.node-version == '20.x'
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'ci: auto fixes, retests, and coverage ✅'
          title: Automated Fix, Test & Coverage Results
          body: |
            ✅ Tests and fixes verified on Node.js 18, 20, and 22.
            📊 Coverage results uploaded to Codecov.
            🧹 Linting & formatting checks completed.
          branch: auto/fix-${{ github.run_number }}
          base: main
    timeout_minutes: 30
  summary:
    needs:
      - build-and-test
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: CI Summary
        run: |
          if [[ "${{ needs.build-and-test.result }}" == "success" ]]; then
            echo "✅ CI pipeline completed successfully across all Node versions."
          else
            echo "❌ One or more matrix builds failed. Check logs above."
          fi
    timeout_minutes: 30
env:
  NODE_VERSION: '18'
  QMOI_AUTODEV_ENABLED: 'true'
