name: Update Coveralls Badge

on:
  workflow_run:
    workflows: ["E2E Tests"]
    types:
      - completed

jobs:
  update-badge:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Update Coveralls badge in README
        run: |
          BADGE_URL="https://coveralls.io/repos/github/${GITHUB_REPOSITORY}/badge.svg?branch=main"
          sed -i "s|\[!\[Coverage Status.*\](.*)\]|[![Coverage Status]($BADGE_URL)]($BADGE_URL)|" README.md
      - name: Create Pull Request for badge update
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: "Update Coveralls badge URL"
          title: "Update Coveralls badge URL"
          body: "Automated update of Coveralls badge URL after coverage upload." 