name: E2E Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run build
      - uses: cypress-io/github-action@v6
        with:
          start: npm start
          wait-on: 'http://localhost:3000'
          wait-on-timeout: 120
      # Upload coverage to Codecov
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # Set in repo secrets if private
          files: ./coverage/lcov.info
      # Upload coverage to Coveralls
      - name: Upload coverage to Coveralls
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ./coverage/lcov.info
      # Notify Slack (advanced logic)
      - name: Notify Slack (on failure)
        if: failure()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "❌ E2E Tests FAILED! Please check the logs and Allure report: https://<your-username>.github.io/<your-repo>/"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      - name: Notify Slack (on success)
        if: success()
        uses: slackapi/slack-github-action@v1.25.0
        with:
          payload: |
            {
              "text": "✅ E2E Tests PASSED! See Allure report: https://<your-username>.github.io/<your-repo>/"
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      # Send email notification (advanced logic)
      - name: Send email notification (on failure)
        if: failure()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "E2E Tests FAILED"
          to: ${{ secrets.NOTIFY_EMAIL_TO }}
          from: ${{ secrets.NOTIFY_EMAIL_FROM }}
          body: "E2E tests FAILED! Please check the logs and Allure report: https://<your-username>.github.io/<your-repo>/"
      - name: Send email notification (on success)
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: ${{ secrets.SMTP_SERVER }}
          server_port: ${{ secrets.SMTP_PORT }}
          username: ${{ secrets.SMTP_USERNAME }}
          password: ${{ secrets.SMTP_PASSWORD }}
          subject: "E2E Tests PASSED"
          to: ${{ secrets.NOTIFY_EMAIL_TO }}
          from: ${{ secrets.NOTIFY_EMAIL_FROM }}
          body: "E2E tests PASSED! See Allure report: https://<your-username>.github.io/<your-repo>/" 
      # Notify Teams
      - name: Notify Teams
        if: always()
        run: |
          npx teams-notify --webhook-url ${{ secrets.TEAMS_WEBHOOK_URL }} --text "E2E Tests completed! See Allure report: https://<your-username>.github.io/<your-repo>/"
      # Notify Discord
      - name: Notify Discord
        if: always()
        uses: Ilshidur/action-discord@master
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          message: "E2E Tests completed! See Allure report: https://<your-username>.github.io/<your-repo>/" 
      # Notify Telegram
      - name: Notify Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: "E2E Tests completed! See Allure report: https://<your-username>.github.io/<your-repo>/"
      # Notify WhatsApp (Twilio)
      - name: Notify WhatsApp
        if: always()
        run: |
          curl -X POST https://api.twilio.com/2010-04-01/Accounts/${{ secrets.TWILIO_ACCOUNT_SID }}/Messages.json \
            --data-urlencode "Body=E2E Tests completed! See Allure report: https://<your-username>.github.io/<your-repo>/" \
            --data-urlencode "From=whatsapp:${{ secrets.TWILIO_WHATSAPP_FROM }}" \
            --data-urlencode "To=whatsapp:${{ secrets.TWILIO_WHATSAPP_TO }}" \
            -u ${{ secrets.TWILIO_ACCOUNT_SID }}:${{ secrets.TWILIO_AUTH_TOKEN }} 