name: CI
'on':
  push:
    branches:
      - main
  pull_request: null
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Step 1
      - uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: npm
        name: Step 2
      - name: Cache node_modules
        uses: actions/cache@v4
        with:
          path: node_modules
          key: node-modules-${{ runner.os }}-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            node-modules-${{ runner.os }}-
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
      - name: Test
        run: npm test
    timeout_minutes: 30
permissions:
  contents: read
  pull-requests: read
  issues: read
env:
  NODE_VERSION: '18'
  QMOI_AUTODEV_ENABLED: 'true'
