name: QMOI CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  verify-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm ci
      - name: Run QMOI Pre-Activity Check
        run: node scripts/qmoi_pre_activity_check.js
      - name: Run QMOI Verifier (self-healing)
        run: node scripts/qmoi_doc_verifier.js verify
      - name: Run linter
        run: npm run lint --if-present
      - name: Run tests
        run: npm test
      - name: Generate coverage report
        run: |
          if [ -f ./node_modules/.bin/nyc ]; then
            npx nyc npm test
          fi
      - name: Upload auto-fix log
        uses: actions/upload-artifact@v4
        with:
          name: auto_fix_log
          path: logs/auto_fix.log
      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage
          path: coverage/
      - name: Upload healing summary
        run: |
          tail -n 20 logs/auto_fix.log > logs/healing_summary.log || true
        continue-on-error: true
      - name: Upload healing summary artifact
        uses: actions/upload-artifact@v4
        with:
          name: healing_summary
          path: logs/healing_summary.log
      - name: Workflow summary
        run: |
          echo '### QMOI Healing Summary' >> $GITHUB_STEP_SUMMARY
          tail -n 20 logs/auto_fix.log >> $GITHUB_STEP_SUMMARY
        continue-on-error: true 