



name: QMOI App Build

on:
  push:
    branches: [main, release/*]

jobs:
  qmoigithub_runner:
    name: QMOI App Build
    runs-on: [self-hosted, qcity]
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/heads/release/')
    env:
      GIT_SUBMODULE_STRATEGY: recursive
      GIT_DEPTH: 1
      NODE_ENV: production
      PYTHONUNBUFFERED: 1
      QMOI_EMAIL_USER: ${{ secrets.QMOI_EMAIL_USER }}
      QMOI_EMAIL_PASS: ${{ secrets.QMOI_EMAIL_PASS }}
      QMOI_EMAIL_RECIPIENT: ${{ secrets.QMOI_EMAIL_RECIPIENT }}
      QMOI_SLACK_WEBHOOK: ${{ secrets.QMOI_SLACK_WEBHOOK }}
      QMOI_TWILIO_SID: ${{ secrets.QMOI_TWILIO_SID }}
      QMOI_TWILIO_TOKEN: ${{ secrets.QMOI_TWILIO_TOKEN }}
      QMOI_TWILIO_WHATSAPP: ${{ secrets.QMOI_TWILIO_WHATSAPP }}
      QMOI_TELEGRAM_TOKEN: ${{ secrets.QMOI_TELEGRAM_TOKEN }}
      QMOI_TELEGRAM_CHAT: ${{ secrets.QMOI_TELEGRAM_CHAT }}
      QMOI_DISCORD_WEBHOOK: ${{ secrets.QMOI_DISCORD_WEBHOOK }}
      QMOI_CODESPACES: "true"
    steps:
      - name: Runner Self-Check & Auto-Fix
        run: |
          echo "🔍 Checking runner health..."
          python scripts/qmoi-runner-selfcheck.py || echo "⚠️ Self-check failed. Attempting fix..." && python scripts/qmoi-runner-autofix.py

      - name: Runner Performance & Reliability Check
        run: |
          python scripts/qmoi-runner-performance.py || echo "Runner performance fallback used."

      - name: Runner Usage Enhancement
        run: |
          python scripts/qmoi-runner-enhance-usage.py || echo "Usage enhancement fallback used."

      - name: Git Sync (no billing-risk)
        run: |
          git config --global user.name "QMOI AutoBuilder"
          git config --global user.email "actions@qmoisystem.com"
          git fetch --all
          git reset --hard origin/$(git rev-parse --abbrev-ref HEAD)

      - name: Ensure Python 3.10+ and Pip
        run: |
          python --version
          python -m pip install --upgrade pip setuptools wheel

      - name: Install Requirements (safe)
        run: |
          pip install -r requirements.txt || true

      - name: Trigger QMOI Build (Local or API)
        run: |
          curl -X POST http://localhost:5050/api/build-apps || (
            echo "🌐 API build failed. Running local builder..." && \
            call setup_and_build_qmoi_ai.bat
          )

      - name: QCity Multi-platform Release Validation
        run: |
          python scripts/qmoi-app-validator.py all || echo "Validation fallback used."

      - name: Archive Binaries to QCity Vault
        run: |
          mkdir -p /qcity-artifacts/QMOI-apps
          cp -r Qmoi_apps/* /qcity-artifacts/QMOI-apps/ || echo "⚠️ No artifacts copied"

      - name: GitHub Sync Done
        run: echo "✅ Build complete and apps synced to QCity + GitHub Releases"
